### ISSUE TITLE
Hero units nested in block sections may not display the correct colors (backgrounds/links)

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express_mono#103]
Lower left hero is set to white ghost button, but the button is black due to it being nested in a block section with a white background.

https://www.colorado.edu/demos/tutorials/admissions

**Comment by kevincrafts** [comment]
I think this might be fixed by #6

**Comment by jwfuller** [comment]
@kevincrafts Can you test to see if this was fixed?

**Comment by kevincrafts** [comment]
Confirmed this was fixed
