### ISSUE TITLE
Temporarily disable the Bundle UI

### ISSUE THREAD

**Issue by jwfuller** [CuBoulder/express_mono#109]
We want to be able to stop the addition of new bundles across the service. 
```
drush vset disable_bundle_ui 1
```
We may need to reconcile what was merged into 3.0.0 and what was merged into 2.10.1 after 3.0 is deployed

**Comment by jwfuller** [comment]
We also want to consolidate any hooks that alter access. 
We already found 2 https://github.com/CuBoulder/express_mono/blob/dev/modules/custom/cu_atlas/cu_atlas.module#L316 and https://github.com/CuBoulder/express_mono/blob/dev/modules/custom/express_content_edit_lock/express_content_edit_lock.module#L196

**Comment by kevincrafts** [comment]
Looks like we already have a way to disable the UI - https://github.com/CuBoulder/express_mono/blob/dev/modules/custom/profile_module_manager/profile_module_manager.module#L465
