### ISSUE TITLE
Eliminate duplicate permissions 

### ISSUE THREAD

**Issue by jwfuller** [CuBoulder/express_mono#110]
Many modules might assign permissions - we should know which permissions are being assigned more than once and consolidate that.

**Comment by kevincrafts** [comment]
This module does not eliminate permissions - only displays a list of modules that provide permissions where the permission has been added more than once.

enable secure_permissions_duplicate
go to admin/config/people/secure_permissions/duplicate

**Comment by kevincrafts** [comment]
Also, this module isn't meant to be enabled on all sites - it's more of a debugging module

**Comment by jwfuller** [comment]
Spoke with @kevincrafts, we decided to hold this PR until all bundles are in and to include a first pass at consolidating permissions
