### ISSUE TITLE
Modules that add new roles leaves blanks when uninstalled

### ISSUE THREAD

**Issue by jwfuller** [CuBoulder/express_mono#112]
An empty add-on role is being created on some sites - Emily reported this to me after the forms bundle had been re-added to her site.  The checkbox has a role ID value that does not exist on the site.

https://www.colorado.edu/bursar-campus-resources/admin/people/invite

![Screen Shot 2019-03-11 at 12 45 14 PM](https://user-images.githubusercontent.com/349713/54149403-ad02b980-43fb-11e9-8b84-8aa64ec3157c.png)

This is caused by uninstalling modules that are adding a role to the list of available add-on roles like in cu_digital_campaign_bundle

We need a better fix for this, but this is really unlikely to happen and can be resolved by resaving admin/config/people/invite.

**Comment by AlanBCole** [comment]
## Steps I took to both replicate and verify this bug:
1. enable the cu_digital_campaign_bundles module
1. go to admin/people/invite
    - check that the campaign manager was added to the Add-on Roles section
1. disable this module
1. enable it again
1. go back to admin/people/invite
    - check for blank radio buttons/check boxes in the Add-on Roles section (hopefully there aren't any now!)
    - check that the campaign manager was added to the Add-on Roles section

This could be repeated for the cu_forms_bundle, too.
