### ISSUE TITLE
Form Editor should be able to add form viewers and form editors with AutoComplete

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express_mono#119]
Auto Complete should work for Form Editors. A Form Editor is supposed to be able to edit the form body, form components and view form submissions, for all forms that are assigned to them.

However, they cannot add form editors or viewers because the auto complete functionality does not work for them. 

Note that Form Editor is a permission level, not a role. 

![formeditor](https://user-images.githubusercontent.com/638275/52502257-915b8780-2b9f-11e9-9da4-4c7207691aa9.jpg)

Note that Auto Complete works for the other roles, such as site owners and site editors. It just does not work for Form Editors. 
![Screen Shot 2019-05-13 at 5 06 25 PM](https://user-images.githubusercontent.com/638275/57659974-987ca200-75a1-11e9-9979-bf30d3ffc9cc.png)

**Comment by kevincrafts** [comment]
I am not able to reproduce this issue right now.

**Comment by cathysnider** [comment]
Auto Complete for Form Managers/Editors is working at this time. 

![Screen Shot 2020-01-28 at 1 24 15 PM](https://user-images.githubusercontent.com/638275/73302281-9ad76880-41d1-11ea-9d6f-f9fddb137660.png)
