### ISSUE TITLE
Google Tag Manager ID not set properly on sites

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express_mono#142]
Recently it was reported that Google Tag Manager wasn't working properly on https://www.colorado.edu/program/maje/

Turns out the GTM ID was missing.

We tracked down this commit: https://github.com/CuBoulder/express/commit/372f2a43d65f491c93ab6d6d644ccf46ddbc9c42

Which adds GTM as a dependency and TRIES to set an ID on existing sites.  Problem is this commit was removed from the codebase before the release was deployed, the function name is wrong so it wouldn't have been added to existing sites, AND there is nothing setting this ID for new sites.

So we need to make sure:
1. google_tag is enabled on all sites
2. The GTM ID (GTM-M3DX2QP) is added to all existing sites
3. The GTM ID is added to new sites as they are installed

**Comment by jwfuller** [comment]
The is feature in Atlas to allow for an override value to be used on dev and test https://github.com/CuBoulder/atlas/issues/530
