### ISSUE TITLE
File Content Type should have a default URL pattern

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express_mono#148]
When someone adds a file to a site with the file content type, the file just ends up at the root of the site.  For some sites this isn't an issue, but it causes problems on the homepage when files are added and conflict with existing redirects.  We should just add a url pattern for all uploaded files to help deal with this issue.

Example:
https://www.colorado.edu/graduate-student-grievance-form-draft-2019
redirects to: https://www.colorado.edu/admissions/graduate-student-grievance-form-draft-2019

**Comment by jwfuller** [comment]
This is about the File content type, not user uploaded files

**Comment by jwfuller** [comment]
It appears that there is a conflict between wildcard redirects both in Drupal and in htaccess

**Comment by jwfuller** [comment]
This would be nice to fix, but @jbertrand determined that this is not high enough impact for the LTS.
