### ISSUE TITLE
Test Content Images Not Working

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express_mono#163]
Because the url for the test content images have a redirect, they don't download and install correctly.

"HTTP error -1002 occurred when trying to fetch https://picsum.photos/1500/1000/?random.
The specified file could not be copied, because no file by that name exists. Please check that you supplied the correct filename."

The resulting url from the redirect is https://picsum.photos/id/317/1500/1000

**Comment by kevincrafts** [comment]
This impacts any of the test content modules that install images from picsum, which include pages, articles, blocks, and gallery.  People uses a different service.

**Comment by jwfuller** [comment]
@kevincrafts Is going to test further on dev environment. We previously had a random generator for this, but that also failed from time to time.

**Comment by kevincrafts** [comment]
Looked at this on dev and the image install fails there too. 

One of the issues that we ran into before is that trying to request an image by an ID doesn't always work because an ID might not exist. Rather than complicate the module with checks to see if an id exists and trying another if it doesn't etc, maybe we should just use a different random image service.

We could replace the existing random image urls with something like: https://placeimg.com/1500/1000/nature which does return just an image.
