### ISSUE TITLE
Choice "New" is gone from Menu Link Target for new menus

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express_mono#165]
This problem is only happening on new menus -- aka, those that are added by the site-builder.  It is **_not_** happening on the pre-installed Express menus (Main, Footer and Secondary).

on admin/structure/menu/manage/my-new-menu, you used to be able to choose a target of "New" from the Target drop down. 

But now we're only getting URL, Placeholder, and Existing Content. 

![Screen Shot 2019-06-10 at 12 03 40 PM](https://user-images.githubusercontent.com/638275/59217044-52076c80-8b7a-11e9-96df-7af40aa87d20.png)

**Comment by cathysnider** [comment]
@kevincrafts Question: We do want to verify that this is a Bug, not a feature update.

**Comment by kevincrafts** [comment]
I don't think this is a new issue. Each content type is configured so you can add it to particular menus. We can only set that configuration for menus that we know exist, so we can not set this for menus that are created by the user.
