### ISSUE TITLE
Test Content Images for Basic Pages need Base URL

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express_mono#223]
When creating test content with the CU Test Content modules, images inserted into Basic Pages don't have a good basic URL set, which results in broken images. 

![Screen Shot 2019-07-29 at 12 48 31 PM](https://user-images.githubusercontent.com/638275/62074225-80f7a180-b1ff-11e9-87df-3781ef8f0ffa.png)

```
<p><img alt="alt text" class="image-slider" src="http://default/sites/default/files/styles/slider/public/nature_16_0?itok=F0ifSOLz" /></p>
```

**Comment by jwfuller** [comment]
Problem may be that `$base_url` is  not correctly set on that particular instance. @cathysnider please work with @jwfuller to test the theory.

**Comment by cathysnider** [comment]
Problem verified on local. 
URL for photo in Basic Pages Test Content is set in modules/contrib/cu_test_content_admin_bundle/cu_test_content_pages.install Line 151.

**Comment by cathysnider** [comment]
https://github.com/CuBoulder/express_mono/blob/dev/modules/custom/cu_test_content_admin_bundle/cu_test_content_pages/cu_test_content_pages.install#L151

**Comment by cathysnider** [comment]
Solution:
Edit local settings.php; 
Uncomment line 315; change base URL to local site {http://mysitename.lndo.site}
