### ISSUE TITLE
CMCI Affiliation label change "&" to "and"

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express_mono#235]
Amanda McManus has asked the CMCI affiliation label to be changed to replace the ampersand with the word "and" which follows their branding of the college.

https://github.com/CuBoulder/express_mono/blob/27516aaf438ff622b0987b9134cd590221efd959/modules/custom/cu_core/cu_core.module#L400

https://www.colorado.edu/cej/

https://www.colorado.edu/cmci/

I wouldn't mind more consistency with this - everything has the ampersand or the and. But that would require that site names would need to be updated as well and I'm not sure about the politics surrounding all of that. (For instance, https://www.colorado.edu/researchinnovation/ would need to be changed to Research and Innovation Office, https://www.colorado.edu/engineering/ would be changed to College of Engineering and Applied Science).

**Comment by kevincrafts** [comment]
Jo checked with Jen and Jon and all colleges and schools should use "and" instead of "&". We will need to coordinate the release with some communication so sites that may need a name change will know it's coming.

**Comment by jwfuller** [comment]
@kevincrafts is going to clarify if this change should be applied to all units

**Comment by kevincrafts** [comment]
Moving this issue to the backlog for now.

While I know that CMCI requested this because they wanted to use "and" instead of "&" they are a rare case of where we are not using "&" in content and further changing other colleges and schools to use "&" only makes the problem worse because that would just makes things even less consistent because there are so many other labels that use "&" all over our sites which should be changed as well, such as:

Academic Success & Achievement Program (ASAP)
Engineering, Math & Physics Library
Gay, Lesbian, Bisexual & Transgender Resources
Student Support & Case Management (SSCM)
University Exploration & Advising Center
Veteran & Military Affairs

**Comment by jbertrand** [comment]
We are talking about affiliations label for this change, not all references within a website. What you list as your examples are not Affiliations or Major units. 

Again, make the "&" to "and" for all the major units in the affiliation label list.  This includes:
College of Arts and Sciences
College of Media, Communication and Information
Office of Diversity, Equity and Community Engagement
Research and Innovation Office
Part of Finance and Business Strategy
Part of Infrastructure and Sustainability
Office of Integrity, Safety and Compliance
Part of Strategic Relations and Communications.
