### ISSUE TITLE
Block Row maximum width

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express_mono#236]
Block rows used to have a maximum width, which allowed them to be put into wide regions but not fully stretch across the browser window.

In the branding update we removed this maximum width, but some sites have used block rows in the wide regions in place of block sections to place block content.

Amanda McManus would like to know if we will fix or not so she can fix if she needs to.

**Comment by jwfuller** [comment]
Customer was unintentionally taking advantage of a bug, we fixed that bug in block row. Customer should update their layouts
