### ISSUE TITLE
Bundle "more info" links are broken

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express_mono#237]
The content these used to link to were on the old web express site and this content does not exist any longer.  While there is Help Scout tutorial content we could link to, it's not certain that this content gives a good representation of what the bundle does and has examples.

These urls are in the info file of each bundle.

https://github.com/CuBoulder/express_mono/blob/dev/modules/custom/cu_advanced_layout_bundle/cu_advanced_layout_bundle.info#L6

**Comment by cathysnider** [comment]
Advanced Content
Advanced Design
Advanced Layout
Alumni Class Notes
Campus News Bundle
Collections
Content Sequence Bundle
CU Live Chat
CU Publications
Express Localist Bundle
Feeds
Forms
Livestream Bundle
Mega Menu Bundle
News and Articles
Newsletter Bundle
People
Photo Gallery Bundle
Responsive Visibility Bundle
Search Engine Optimization
Section Page
Social Media
Video Hero Unit Bundle
CU Countdown Bundle
