### ISSUE TITLE
Create a new repo for the debug bundle

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express_mono#242]
The modules in the debug bundle are still needed for local development - we just don't need to have them deployed to the other environments.  Creating a new repo for the cu debug admin bundle and all of its optional dependencies will still give us the tools to install locally.

https://github.com/CuBoulder/express_mono/tree/dev/modules/custom/cu_debug_admin_bundle

Optional dependencies are listed at https://github.com/CuBoulder/express_mono/blob/dev/modules/custom/cu_debug_admin_bundle/cu_debug_admin_bundle.info

**Comment by cathysnider** [comment]
The new repo is here: https://github.com/CuBoulder/cu_debug_admin_bundle

**Comment by jwfuller** [comment]
https://github.com/CuBoulder/cu_debug_admin_bundle
