### ISSUE TITLE
Fix Form Submitter Role: allow Form Submitter to be deleted or promoted

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express_mono#244]
Background:
A client (Registrars office) requested a way to clear up form submitter accounts on a site or be able to filter to exclude the form submitter users from the page view to "clear" up the user admin page clutter and make it easier to manage users with editing roles.

Use case scenario:
Sometimes, a form creator wants to hide their form behind a login, so that only users with an IdentiKey can fill out the form. 
Example: https://www-test.colorado.edu/p1adc0679b79/content/contact-us
The Form Submitter role is a **stand-alone** role, not an add-on role, that is assigned to an authenticated user when they login in order to submit a webform. 
Original PR: https://github.com/CuBoulder/express/pull/2938

Currently, there is a dependency with the role compared to other role management features that a site owner may do:

1) An administrator, site owner and site editor with access management permissions should be able to edit **a user with** the role in order to cancel the account or promote the user to greater privileges. 
 

![editUser](https://user-images.githubusercontent.com/638275/63293122-82f3d400-c284-11e9-9611-9d3cf4f9ef86.gif)

**Comment by kevincrafts** [comment]
If you delete the role I think it would just get added again the next time they logged in. If the role was not re-added, it would mean a user could never use that role functionality again on that site. Since this seems to be meant for site visitors that have no roles but are able to authenticate, I don't know that we should be making something that would ban a student or employee from accessing a form that requires authentication.

**Comment by cathysnider** [comment]
I apologize for lack of clarity. I do not mean that the ROLE should be deletable; I mean a user with the role should be deletable. Currently, users with the FS role cannot be removed from a site. A site owner should be able to remove users with the FS role.

**Comment by ekellagher** [comment]
There might be a use case that a CU employee or student has left and no longer has an identikey, the request to delete form submitter would be in an effort that site owners could delete old users every year or so to clean up this large user block. It would not hurt that they got added back to the site but it may help to keep this block of users to a manageable size

**Comment by cathysnider** [comment]
Requirements for the Form Submitter Role were fleshed out through discussion but were not documented very well in the ticket, other than by the test criteria. https://github.com/CuBoulder/express/pull/2938#issuecomment-427119709   

 - [ ] Role gets no editing or creating privileges
 - [ ] User is listed on admin/people with role 'form_submitter'
 - [ ] User appears on "Promote Existing Users" tab (/admin/people/promote) and can be given a real role on the sit

**Comment by cathysnider** [comment]
Notes on usage: When a Form Submitter who has submitted a form is deleted, the form submission continues to exist. The 'Submitted by' information changes from 'FirstName LastName' to "Anonymous" . This is not a problem because the important information gathered in the form itself. 

![submission5a](https://user-images.githubusercontent.com/638275/63543773-cb0f3280-c4e0-11e9-8641-2cde6ffe990b.jpg)

![submission5b](https://user-images.githubusercontent.com/638275/63543795-d7938b00-c4e0-11e9-8740-3baf39e826c8.jpg)

**Comment by jwfuller** [comment]
@jwfuller To review

**Comment by jwfuller** [comment]
Feature request to cancel Form submitter account is a good one.
