### ISSUE TITLE
Remove light heading option from theme settings

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express_mono#250]
We should remove this theme option and make all headings bold, because:

1. We've started getting reports from Google that some of these light headings are difficult to read.
2. Smaller headings are harder to differentiate from regular text

**Comment by jwfuller** [comment]
Kevin is getting reports from Google

**Comment by kevincrafts** [comment]
I have access to the site report but according to Jo it's no longer showing the error she saw a few weeks ago.
