### ISSUE TITLE
Link color is white in a white button link shortcode placed within text of slider

### ISSUE THREAD

**Issue by johnquest** [CuBoulder/express_mono#258]
This occurs in each of the 5 style settings for placement of text within sliders.

**Comment by kevincrafts** [comment]
To test, add a button shortcode with color set to white to the slider teaser field

Before:
![Screen Shot 2019-09-04 at 10 20 08 AM](https://user-images.githubusercontent.com/349713/64273067-d0677680-cefd-11e9-82bc-419869b571f0.png)

After
![Screen Shot 2019-09-04 at 10 21 34 AM](https://user-images.githubusercontent.com/349713/64273068-d0677680-cefd-11e9-8565-9b38c8942a34.png)
