### ISSUE TITLE
Import express_mathjax_bundle

### ISSUE THREAD

**Issue by jeor0980** [CuBoulder/express_mono#26]
https://github.com/CuBoulder/express_mathjax_bundle

**Comment by kevincrafts** [comment]
This bundle requires a few manual steps to enable, some which require Developer access:
1. Enable the Bundle
2. Add the MathJax filter to the WYSIWYG Text Format
3. Clear cache

**Comment by jwfuller** [comment]
In the current state, the result is an overridden feature. 

Possible solutions:
1. Handle this a package in Atlas and do not add to monolith
2. Make part of core WYSIWYG feature and enable for all sites

**Comment by kevincrafts** [comment]
Another way we can handle this that would NOT result in an overridden feature is to make a NEW MathJax enabled text format that the user would have to select on the field.

**Comment by jwfuller** [comment]
Spoke with Jo, she indicated that we could deprecate this functionality.
