### ISSUE TITLE
Real Name display currently only works with LDAP

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express_mono#261]
The display of user's real names in a site currently has a dependency on us using LDAP. As we move more sites to Pantheon, where we will use a SSO approach instead, getting the real names from LDAP will not be possible.

Real names are displayed on dashboards, user lists, and content lists.

The real name module works by configuring a token to use as the real name value. If SSO could provide a similar token, all we would need to do is update the token value and the implementation of real name could remain the same.

![Screen Shot 2019-09-04 at 10 46 16 AM](https://user-images.githubusercontent.com/349713/64275075-ff7fe700-cf01-11e9-879e-60e726ed9965.png)

Related to #259

**Comment by kreynen** [comment]
I don't know if this is helpful, but a bit of history on this...

1. You can use LDAP from Pantheon. You just can't bind as the user authenticating and have access to fewer values.  https://github.com/CuBoulder/express_mono/blob/27516aaf438ff622b0987b9134cd590221efd959/modules/features/cu_ldap/cu_ldap.module#L100 currently users the cu_ldap_default_ldap_servers and relies on functions in the contrib LDAP project, but this can be modified to be populate from a variable and leverage PHP's <a href="https://www.php.net/manual/en/function.ldap-search.php">ldap_search</a>.  You can also populate these fields with data from the SAML response, but that only happens for the user logging in. It wouldn't be able to replace https://github.com/CuBoulder/express_mono/blob/27516aaf438ff622b0987b9134cd590221efd959/modules/features/cu_ldap/cu_ldap.module#L176
2. The tokens are based on fields created when LDAP was added and then populated with LDAP during the authentication, but don't require LDAP. I think I added those and just wasn't thinking beyond using LDAP for the values. The fields and tokens are defined in https://github.com/CuBoulder/express_mono/blob/27516aaf438ff622b0987b9134cd590221efd959/modules/features/cu_ldap/cu_ldap.features.field_instance.inc#L14 and can still be used by realname even if contrib LDAP module is disabled. It will be confusing to leave ldap_ in the field name, but less work than completely refactoring this.

**Comment by jwfuller** [comment]
Duplicated by https://github.com/CuBoulder/express_mono/issues/294
