### ISSUE TITLE
Support Wowza live stream embeds

### ISSUE THREAD

**Issue by jwfuller** [CuBoulder/express_mono#289]
We want to replace the cu_livestream bundle with one that targets this service. https://www.wowza.com/docs/getting-started-with-wowza-player

**Comment by kevincrafts** [comment]
`<HTML>
<HEAD>
	<title>My Wowza Player Video</title>
	<script type="text/javascript" src="//player.wowza.com/player/latest/wowzaplayer.min.js"></script>
</HEAD>

<BODY>

	<div id="playerElement" style="width:100%; height:0; padding:0 0 56.25% 0"></div>

	<script type="text/javascript">
	WowzaPlayer.create('playerElement',
		{
		"license":"[wowza-player-license-key]",
		"title":"My Wowza Player Video",
		"description":"This is my Wowza Player Video description.",
		"sourceURL":"http://[wowza-ip-address]:1935/vod/sample.mp4/playlist.m3u8",

                "autoPlay":false,
		"volume":"75",
		"mute":false,
		"loop":false,
		"audioOnly":false,
		"uiShowQuickRewind":true,
		"uiQuickRewindSeconds":"30"
		}
	);
	</script>
<BODY>
</HTML>`

**Comment by jwfuller** [comment]
`PLAY2-j7edh-vmrnJ-FG9DU-M9Uhy-QaM8k`

HLS player 
```
<script type="text/javascript" src="//player.wowza.com/player/latest/wowzaplayer.min.js"></script>
<script type="text/javascript">
WowzaPlayer.create('playerElement',
    {
    "license":"",
    "title":"",
    "description":"",
    "sourceURL":"",
    "autoPlay":false,
    "volume":"75",
    "mute":false,
    "loop":false,
    "audioOnly":false,
    "uiShowQuickRewind":true,
    "uiQuickRewindSeconds":"30"
    }
);
</script>
```
Low Latency Player
```
<script type="text/javascript" src="//player.wowza.com/player/latest/wowzaplayer.min.js"></script>
<script type="text/javascript">
WowzaPlayer.create("playerElement",
    {
    "license":"",
    "sources":[{
    "sourceURL":""
    },
    {
    "sourceURL":""
    }],
    "title":"",
    "description":"",
    "autoPlay":false,
    "mute":false,
    "volume":75
    }
);
</script>
```

**Comment by kevincrafts** [comment]
After working with Wowza on the Commencement steam I understand more about their platform and which embed we should be using.

I think we can make this easy to use by creating a video filter codec that will allow users to use the existing video embed and have it work with this service.
