### ISSUE TITLE
Button text color not correct on card style content grids

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express_mono#292]
This bug is a result of fixing a previous issue #232. The solution was more of a sledgehammer approach to make sure link colors would be correct, but that also made the text color of buttons change.

Before:
![Screen Shot 2019-09-19 at 3 45 18 PM](https://user-images.githubusercontent.com/349713/65283501-86cd7d00-daf4-11e9-9dc7-dfb7b3a2cbe0.png)

After:
![Screen Shot 2019-09-19 at 3 45 02 PM](https://user-images.githubusercontent.com/349713/65283516-8cc35e00-daf4-11e9-9910-a98aab0953dc.png)

**Comment by kevincrafts** [comment]
To test, create a content grid with the card style and add a button in the text area.

**Comment by jcsparks** [comment]
Sorry to re-open this but Emily believed dark buttons with dark text would have been fixed along with this issue but it's still having issues with dark buttons having dark text on them.  e.g. https://www.colorado.edu/webcentral/training

**Comment by jbertrand** [comment]
She needs to look on www-test not production for the changes. Check out dark buttons here:
https://www-test.colorado.edu/engineering/

**Comment by jwfuller** [comment]
Closing since this seems to be fixed.
