### ISSUE TITLE
Bug: Hero Image breaking out of content area

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express_mono#312]
An image placed as size Hero on a node or with Feature Layout breaks out of the left side boundary. And is significantly offset.

This issue has been dealt with before: See Express 2997
https://github.com/CuBoulder/express/issues/2997 

In Prod: 
Basic Page: https://www.colorado.edu/demos/cathys-sandbox/webexp-design/image-styles-testing
Article: https://www.colorado.edu/demos/cathys-sandbox/2016/06/28/article-feature-layout

![Screen Shot 2019-10-02 at 1 57 39 PM](https://user-images.githubusercontent.com/638275/66077460-47a02280-e51d-11e9-98ce-6dcd78e3715b.png)

**Comment by kevincrafts** [comment]
This is only an issue on some themes (themes which are not full width by design - NOT themes that are set to be boxed in the theme settings).

**Comment by cathysnider** [comment]
Only one theme is not full width by design (i.e. is 'boxed' by design): Shadow
