### ISSUE TITLE
Link Color not working on some Hero Units

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express_mono#313]
The link color is not kicking in on some of the Hero Units: 
Specifically, those with background color of Medium Blue, Dark Blue, Light Green and Brick. 

Link should look like a button. See 'Light Blue Background' example.

https://www.colorado.edu/demos/cathys-sandbox/colors/hero-unit-background-colors

![Screen Shot 2019-10-04 at 1 50 07 PM](https://user-images.githubusercontent.com/638275/66235705-ecea0080-e6ad-11e9-8320-b8e9438be7d0.png)

**Comment by kevincrafts** [comment]
This is because the url field was left blank so it only displays the text and doesn't make it a link.

**Comment by cathysnider** [comment]
Further testing reveals that when the URL is filled in, the Link Button shows up as it should. Solved!
![Screen Shot 2019-10-07 at 11 56 42 AM](https://user-images.githubusercontent.com/638275/66336132-bf919280-e8f9-11e9-824f-e9fa3f62d33d.png)
