### ISSUE TITLE
Some Social Link blocks have underlined icons

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express_mono#314]
In some color backgrounds, the social links icons have underlines. 

In this example, the same block was placed on different colored Block Sections:
https://www-dev.colorado.edu/brandtest/blocks/colored-block-sections-social-links

When the block is on backgrounds Brick, Medium Blue, Dark Blue and Gold, the icon has an underline.
![Screen Shot 2019-10-04 at 4 35 04 PM](https://user-images.githubusercontent.com/638275/66244335-211ceb80-e6c5-11e9-9684-441bffd1b1f5.png)
![Screen Shot 2019-10-04 at 4 35 11 PM](https://user-images.githubusercontent.com/638275/66244336-21b58200-e6c5-11e9-9cd9-cf9bb7edef34.png)
![Screen Shot 2019-10-04 at 4 35 25 PM](https://user-images.githubusercontent.com/638275/66244337-21b58200-e6c5-11e9-932f-fc1594fbf51c.png)
![Screen Shot 2019-10-04 at 4 35 30 PM](https://user-images.githubusercontent.com/638275/66244338-21b58200-e6c5-11e9-8a47-8b844808e4f5.png)

**Comment by kevincrafts** [comment]
Adding this for future reference...

ul.social-links.soc > li > a:link,
ul.social-links.soc > li > a:visited {
  text-decoration:none;
}
