### ISSUE TITLE
Stuttering on parallax image banners on firefox

### ISSUE THREAD

**Issue by jeor0980** [CuBoulder/express_mono#316]
For some reason on Firefox images stutter when scrolling:

Example: https://www.colorado.edu/engineering/bold-center/bold-news-events

**Comment by kevincrafts** [comment]
I did some testing with this issue this morning. I created a simple html page and I'm not getting this issue, so there's something else that is interfering with this that may be causing the issue.

**Comment by jwfuller** [comment]
Dev team discussed. Vanilla doesn't have this issue. Not worth the time to debug
