### ISSUE TITLE
www-test: CU Today - 'Articles Grid List' block is broken

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express_mono#317]
https://www-test.colorado.edu/today/news-headlines

Not pulling in articles.
![Screen Shot 2019-10-08 at 4 55 23 PM](https://user-images.githubusercontent.com/638275/66439317-7706d180-e9ec-11e9-994b-bcaac367ee01.png)

**Comment by jwfuller** [comment]
Instance was missing code.
