### ISSUE TITLE
Large, medium, and small image styles are not flushed - update 7004 in cu_image_styles

### ISSUE THREAD

**Issue by johnquest** [CuBoulder/express_mono#328]
image module - Illegal string offset 'name' image.module:985

**Comment by jwfuller** [comment]
@kevincrafts Is going to talk with @johnquest further

**Comment by kevincrafts** [comment]
Looking into this further it seems that we have been modifying image styles wrong though I'm not sure why we haven't identified this issue before.

The correct way to do this is to pass the image style array to the flush function, not just the name:

$style = image_style_load('medium');
image_style_flush($style);

We have only used these in update functions that have already run, so at this stage we do not have current code that is trying to do any of this, however it would be good to go back and update the previous update hooks to run correctly.

**Comment by johnquest** [comment]
I see where you're going and what is fixed. I didn't pick up on the issue until I updated sites to Express mono 4.0 and had missed the issue that occurred earlier updates.
