### ISSUE TITLE
Form Ownership change

### ISSUE THREAD

**Issue by ekellagher** [CuBoulder/express_mono#331]
I logged into [a site](https://www.colorado.edu/cisc/) to help a client with a form (https://www.colorado.edu/cisc/content/2019-ignite-social-justice-conference) and when I saved the form it changed the authoring information to my user account and not the original form owner.

I added a user to view form submissions and then clicked save

This should not be the case

I also had a site owner say they could not edit a form that I created with them on their site

**Comment by jwfuller** [comment]
Tested with @ekellagher, this seems to be specific to her computer.
