### ISSUE TITLE
Include Content Editor (Edit Only) in Atlas Statistics User Report

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express_mono#352]
The Atlas Stats do not include our new Content Editor (Edit Only) in the list of users, though they do include Content Editor (deprecated)

User List Example
Content Editor (edit only) are Bolei, Finnarn and Kellagher.
Content Editor (deprecated) are Crafts, Fuller and Leslie.
![Screen Shot 2019-10-22 at 2 44 59 PM](https://user-images.githubusercontent.com/638275/67331816-76396980-f4db-11e9-8eda-22c43090fa13.png)

Atlas Stats: Those with Content Editor (Edit Only) role are not included. (this screenshot from /admin/config/development/atlas/statistics.
![Screen Shot 2019-10-22 at 2 46 24 PM](https://user-images.githubusercontent.com/638275/67331908-99fcaf80-f4db-11e9-9cb4-2dcabc8793ee.png)

Atlas Stats SML screenshot
![Screen Shot 2019-10-22 at 2 54 54 PM](https://user-images.githubusercontent.com/638275/67332375-28713100-f4dc-11e9-9504-90174dd006e5.png)

**Comment by jwfuller** [comment]
Relates to https://github.com/CuBoulder/express_mono/issues/105
