### ISSUE TITLE
Slider Style 2 (Right Side Content Overlay) - links aren't designated in some themes

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express_mono#355]
In some themes, the links in slider content are not visually designated. They look like plain text. The sighted reader can't tell they are links. 

In a few themes, the links are underlined. (Highlight, Ivory, Layers)
In the rest of them, the links look like text. 

![Screen Shot 2019-10-23 at 11 35 02 AM](https://user-images.githubusercontent.com/638275/67419451-f4ece000-f589-11e9-9cd9-101f3d2e2bc3.png)

**Comment by kevincrafts** [comment]
Was not able to reproduce after creating a slider with links in the text wysiwyg field and testing on multiple themes
