### ISSUE TITLE
Adding Image Help link is broken

### ISSUE THREAD

**Issue by ekellagher** [CuBoulder/express_mono#362]
The Adding Image Help link is broken. It goes to "https://www.colorado.edu/webcentral/node/458" 
It should go to "https://websupport.colorado.edu/category/165-images"
![image help](https://user-images.githubusercontent.com/16137919/68047816-d5019e80-fca4-11e9-8d5d-56ef3b98334b.JPG)

**Comment by jwfuller** [comment]
Duplicates https://github.com/CuBoulder/express_mono/issues/324
