### ISSUE TITLE
Block icon settings in Theme Configuration do not work in Highlight Theme

### ISSUE THREAD

**Issue by ekellagher** [CuBoulder/express_mono#363]
I was trying to see which block icon settings take priority when you configure the block icons in the Theme configuration settings.
On this site, the Hightlight theme is set and I changed the block icon settings to gold
https://www.colorado.edu/demos/experimentation/admin/theme/config/cuhighlight

I created two pages one with no block style and icon color set to default and another page with a block style selected and the block icons remained the same color as the text (the default)
https://www.colorado.edu/demos/experimentation/general-examples/block-icons-0
and
https://www.colorado.edu/demos/experimentation/general-examples/block-icons

The block icons configuration in the theme does not appear to be working

**Comment by jwfuller** [comment]
@kevincrafts Is going to test to see if this impacts one or all themes. He thinks this is likely a long standing bug

**Comment by kevincrafts** [comment]
I've tested other themes and this issue is present in all of them.

**Comment by kevincrafts** [comment]
Talked with Jo - we have decided since this functionality was replaced by another module and it has been so long since anyone even noticed it didn't work any longer we will remove this functionality from the theme. #434
