### ISSUE TITLE
Create shortcode to embed Math Department calendar

### ISSUE THREAD

**Issue by ekellagher** [CuBoulder/express_mono#364]
Not sure if you could expand the Google Calendar parameters to include a custom feed for the Math Department or if you need to create a new shortcode or embed.

The Math Department runs its own calendar platform with an archive of about 9 years of events. This would be too hard to upload to Localist and it seems Google calendaring does not offer the functionality they need.

The calendar they host is at: https://math.colorado.edu/seminars/

New Feature Request criteria for evaluating services were developed for integrations request
1. Is this service accessible? **- not sure**
2. Is this service secure? **- not sure (department run - maybe on OIT infrastructure)**
3. Would this service be used by a large number of Web Express sites or high traffic sites? **no**
4. Does the service provide accurate documentation? **no documentation**
5. Is the service used by a large number of other sites? (Are we one of the first?) **exclusive to Math Department**
6. Is there a community where issues with the service are openly discussed? (Are we seeing feedback from real users or just marketing material?) **just requested from Math Department**
7. Does the service provide a status page and log outages with explanations? **no**
8. Does the service provide roadmaps and timeline for updates? **no**
9. Does the service provide access to test and provide feedback about updates before they are released? **- probably**
10. Does the service provide support? (At both the developer and end user level?) **- Math IT Specialist** 
11. Can we track the status of support requests? **N/A**
12. Does the service have an existing Drupal integration that is reporting several installs and appears to be well supported? **- similar to google calendar shortcode would just need to modify to accept calendar feed URL**

Contact: Jeff Taylor
IT Specialist / Department of Mathematics
303-492-9094 / Jeff.J.Taylor@Colorado.EDU

[HelpScout Ticket](https://secure.helpscout.net/conversation/995797776/2106?folderId=1414566))

**Comment by jwfuller** [comment]
Since this is would be a single use feature and there is a supported campus tool (Localist) we are not going to do this.
