### ISSUE TITLE
Update logout buttton to work with SSO

### ISSUE THREAD

**Issue by jeor0980** [CuBoulder/express_mono#385]
Currently the logout button in express points to `www.colorado.edu/user/logout` which is the way to log out if the user is authenticated via saml.

The logout button needs to redirect to https://fedauth.colorado.edu/idp/profile/Logout now that SSO is in place.

Note: We can start testing this by adding a separate button for SSO logout in the user navigation bar.

**Comment by kevincrafts** [comment]
Since we found out that the OIT provided logout service doesn't actually work, we were advised to just kill the sessions on our end, which the simplesaml module already does with a logout hook.
