### ISSUE TITLE
Prevent GTM from loading on node/*/layout pages

### ISSUE THREAD

**Issue by johnquest** [CuBoulder/express_mono#386]
Can a path be added to google tag manager configuration to prevent it from loading on layout edit pages?

**Comment by kevincrafts** [comment]
In the configuration interface for the Google Tag module, you can specify paths to not be included.  Are you running into issues by having it included on the layout forms?

**Comment by johnquest** [comment]
Yes, one of our site owner's containers is causing a conflict. I did add the path via the interface but can it be added within an express setting or update outside the contrib gtm module? I'm thinking the issue might appear again in other sites on layout pages.

**Comment by kevincrafts** [comment]
Looking at our configuration, we are already excluding 'node/*/*' which should match node/*/layout
