### ISSUE TITLE
Implement integration with experts.colorado.edu

### ISSUE THREAD

**Issue by jeor0980** [CuBoulder/express_mono#41]
https://github.com/CuBoulder/cu_faculty_publication_bundle

**Comment by jwfuller** [comment]
@kevincrafts and I spoke with people in ODA/FIS about features that they would like to see in our implementation. They mentioned that other folks are working on a Wordpress implementation as well.

# Features

- v1.0
    - Create a block where you can select to show publications for an Author or an Organization
    - Include the ability to filter by year (range, this year, specific year)
    - Collaborate with FIS and other implementors to develop a unified look and feel
    - Implement a feature to allow a block to be activated on a Person page that will provide a publications block (help organizations quickly take advantage of the feature)
    - Degrade gracefully using the experts.colorado.edu status page
    - Develop process for delivering feedback on data to FIS (perhaps into their JIRA instance)
    - Investigate Analytics, FIS would like to be able to report on usage and impact
- v1.1
    - Allow for searching for multiple Authors or Organizations
- Future
    - Integrations with visualization tools
    - Additional integrations with the Person index
    - Develop support for users to select citation format

# Resources

- people index - https://experts.colorado.edu/es/fis/_search
- publications index - https://experts.colorado.edu/es/fispubs-v1

The `id` for on a person record is from an FIS database. They can provide a private API for cross-referencing an ID value in UIS data warehouse. The `id` for a person can also be added to publications index.

People can be looked up by email address.

----

- https://github.com/cu-boulder/expertsdirect-facetview
- https://ibs-cupc.colorado.edu/publications-test/

There is also an existing JS implementation of faceted search that we can reference.

**Comment by jwfuller** [comment]
Kevin and I talked about implementation and discussed also discussed ways to improve the editor experience particularly at the organization level. We want to leverage the Person content type, and may also look into utilizing a taxonomy for grouping people.

**Comment by jwfuller** [comment]
FIS is looking at Zotero for citation formats, we may be able to use their [API](https://www.zotero.org/support/dev/web_api/v3/start)

**Comment by AlanBCole** [comment]
I have some questions/comments related to some of the issues in this epic:

1. #520 refers to an Organization ID. What is this? I have not seen it in searches either fispubs-v1 or fis indices. 
2. #519 (and #523?) There is no email field in the publications index (fispubs-v1). 
3. #532 What is a person type?

**Comment by jwfuller** [comment]
@AlanBCole Do you still have the above questions? If so, can you ask them in the relevant issues

**Comment by cathysnider** [comment]
Test site on Dev: https://www-dev.colorado.edu/facultypublications/ 
updated June 3 with commit 2538e9a4f02da12707296ef06b7dd637ac991b61

**Comment by cathysnider** [comment]
Feature Review

- v1.0

 [ ] Create a block where you can select to show publications for an Author or an Organization
 [ ] Include the ability to filter by year (range, this year, specific year)
 [ ] Collaborate with FIS and other implementors to develop a unified look and feel
 [ ] Implement a feature to allow a block to be activated on a Person page that will provide a publications block (help organizations quickly take advantage of the feature)
 [ ] Degrade gracefully using the experts.colorado.edu status page
 [ ] Develop process for delivering feedback on data to FIS (perhaps into their JIRA instance)
 [ ] Investigate Analytics, FIS would like to be able to report on usage and impact
 
- v1.1

 [ ] Allow for searching for multiple Authors or Organizations

**Comment by jwfuller** [comment]
Closed for https://github.com/CuBoulder/express_mono/milestone/3
