### ISSUE TITLE
Update express_content_edit_lock module to work on Pantheon

### ISSUE THREAD

**Issue by jeor0980** [CuBoulder/express_mono#420]
Currently setting `express_content_edit_lock` to `TRUE` and authenticating with SSO will result in a Drupal white screen error `user_logout_current_user() is undefined`, and the user will be authenticated if they return to the site.

The current code also redirects back to `/user` after attempting to log in, resulting a in redirect loop between `/user` and SSO.

**Solution:**

Make these changes to in `express_content_edit_lock.module`
- Add `module_load_include('pages.inc', 'user')` to `express_content_edit_lock_user_login` function
- In `express_content_edit_lock_user_login` remove `/user` parameter from `drupal_goto()`

**Comment by jwfuller** [comment]
Create issue about refactoring this module for SSO

**Comment by cathysnider** [comment]
On DEV: https://www-dev.colorado.edu/p1f3290ba2b7/
