### ISSUE TITLE
Update affiliation for instances that do not currently have it set

### ISSUE THREAD

**Issue by jwfuller** [CuBoulder/express_mono#422]
Variable that we need to set is `cu_site_affiliation_options`. Atlas is the authoritative source for `major_unit` which is what we are using to populate affiliation when it is not set. The instance is intended to be the authoritative source for affiliation.   

Possible solutions:

1. Manually run series drush commands that check if variable is set and set it if not
1. Write an update hook that can get that value from Atlas and set it if necessary

Second way is more robust, first way is faster. Intention is to flip feature flag for this as part of the January release.

**Comment by kevincrafts** [comment]
There are many sites that will not have this set, so I'm not sure a programatic setting of this is a good idea.  While we do have a need of knowing who is the top tier owner of each site, this has different use cases where either custom values or no values for affiliation are possible.  

I argued with Kevin Reynen about this many times as he tried to have the site affiliation value and the sites top tier owner be the same thing, which is some cases it is not.

**Comment by jwfuller** [comment]
We will do this in an update hook

**Comment by kevincrafts** [comment]
We're going to rework this to use the keys from ATLAS, which will also require us to add an update hook to update these keys for sites that already have the values set.
