### ISSUE TITLE
Mega Menu not showing menu links

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express_mono#447]
The update to the Field Collection module has resulted in Mega Menus not rendering the lists of links properly. (https://github.com/CuBoulder/express_mono/commit/4cb7609e7b30553a1918d6555a304116c3252a73)

While I did test some of our uses of Field Collections (Content Grid, Social Icons), Mega Menu was not one that I tested.

Example site:
https://www.colorado.edu/p1b11e444fd7/

**Comment by kevincrafts** [comment]
I think I've gotten it narrowed down to the hook_entity_preload function at https://github.com/CuBoulder/express_mono/blob/dev/modules/contrib/field_collection/field_collection.module#L932

Unfortunately this function did not exist in the previous version and is 60 lines of code to look through.

**Comment by kevincrafts** [comment]
So in looking through this further is that the key being used on this array is not unique so the value continues to get reset.  The odd thing I'm not understanding is that while this is impacting nested field collections for megamenus, it is not impacting nested field collections anywhere else (FAQ pages, Newsletters).

I've tested changing the code from $items[$e->item_id] = $field_data[$langcode]; to $items[] = $field_data[$langcode]; and this does fix the issue and does not seem to have any negative impact on any other uses of field collections.

So I think our options at this point would be either to roll back to the version we were using, or create a patch for this code change.

https://github.com/CuBoulder/express_mono/blob/dev/modules/contrib/field_collection/field_collection.module#L974

**Comment by jwfuller** [comment]
@kevincrafts Is going to update and close this ticket

**Comment by kevincrafts** [comment]
We discovered that new mega menu entities that were created after this update was deployed did not have this issue, and because we only had a single live production site that was using these, we deployed the update and recreated the mega menu entities manually.
