### ISSUE TITLE
Add warning to status page if features are overridden

### ISSUE THREAD

**Issue by jwfuller** [CuBoulder/express_mono#449]

**Comment by kevincrafts** [comment]
There are some features that will get overriden, such as cu_sitewide (https://github.com/CuBoulder/express_mono/tree/dev/modules/features/cu_sitewide) where we provide the sitewide context that places the subnavigation bar but allow users to add to or alter it.

**Comment by jwfuller** [comment]
Relates to #477

**Comment by AlanBCole** [comment]
@kevincrafts do you have any steps to take that would show how a feature gets overridden? Or any other advise and or context for looking into this issue? Thanks!

**Comment by jwfuller** [comment]
@AlanBCole If you modify the configuration for a content type like Basic Page, it should override the feature
