### ISSUE TITLE
Missing content from entities that use field collections

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express_mono#452]
We were notified of an issue with the Financial Aid site where a content grid on their site did not display or contain all the content that existed before the 4.1.2 update. 

https://secure.helpscout.net/conversation/1036391460/2411/?

We think that this is related to an update hook that "Update revisions created before revision support was implemented."

We are not seeing this on every entity that uses field collections, so our initial thinking is this is only happening on blocks/nodes that were created a long time ago (~2017).

**Comment by kevincrafts** [comment]
Manual fix: 

1. Go to edit the block (DO NOT CHANGE ANYTHING OR SAVE)
2. Click on the Revisions link in the blue bar
3. Scroll to the bottom to the revision that is marked as the Current Revision
4. Edit that revision
5. Confirm the content is in the fields
6. Save

**Comment by jwfuller** [comment]
Documented workaround is our answer
