### ISSUE TITLE
Check to see how WYSIWYG will work in Pantheon

### ISSUE THREAD

**Issue by jwfuller** [CuBoulder/express_mono#472]
https://github.com/CuBoulder/express_mono/blob/27516aaf438ff622b0987b9134cd590221efd959/modules/features/cu_wysiwyg/cu_wysiwyg.module#L24

**Comment by cathysnider** [comment]
The function _create_cu_pathologic_paths() isn't called, or has no effect, or something.

What I did: Using terminus drush, I set variable cu_path to commencement. Relative links such as "/node/2" did not go offsite to https://www.colorado.edu/commencement/node/2 as they should have; but stayed on my pantheon dev site https://dev-cathy-test-site.pantheonsite.io/one. Next, I set the variable cu_sid to p1f4bca2b935. Relative links such as "/node/2" did not go offsite to https://www.colorado.edu/p1f4bca2b935/node/2 but stayed on my pantheon dev site. 

Note: I tested my terminus/drush connection and functionality by using it to change the variable site_name to "Two Word Site Name" and the variable theme_default to cushadow. Both actions were successful.
