### ISSUE TITLE
Revert Features

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express_mono#477]
It looks like it's been > 9 months since we last ran the feature revert function on express sites (cu_core_revert_features()) - might not be a bad idea to add this to the next release update hook to make sure as many features as possible get back to their default state.

**Comment by jwfuller** [comment]
I am worried that doing this globally may have unintended consequences. I think we should consider logging this as an error and resolving on a case by case basis.

**Comment by kevincrafts** [comment]
We are going to move forward with #449 to get a better sense of how many features are actually overridden on sites. We may reopen this ticket if if is seen to be the best solution if we have a large number of overridden features.
