### ISSUE TITLE
Block Titles: In Rise Theme, most block titles are not displaying correctly

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express_mono#489]
In Rise Theme, the block titles appear as rectangle boxes in a different color than the block body.

They aren't doing that anymore.
![riseBlockTitles](https://user-images.githubusercontent.com/638275/75476042-1fdfaa00-5957-11ea-8af1-f05b40b943c2.jpg)

https://www.colorado.edu/demos/cathys-sandbox/color-checks/block-row-colors

**Comment by kevincrafts** [comment]
When we updated blocks to use the styles from the base theme, this theme still used the old classes which had been removed.
