### ISSUE TITLE
Shadow Theme: Hero Units once again breaking out of the content area

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express_mono#490]
This problem continues to rear its ugly head
See the problem in the wild:
https://www.colorado.edu/demos/cathys-sandbox/2016/06/28/article-feature-layout
https://www.colorado.edu/demos/cathys-sandbox/content-types/basic-page/basic-page-feature-layout

![Screen Shot 2020-02-27 at 12 50 48 PM](https://user-images.githubusercontent.com/638275/75481141-ccbe2500-595f-11ea-84d0-ff92ab635c45.png)

(It's been solved before: https://github.com/CuBoulder/express/issues/2852)

**Comment by kevincrafts** [comment]
I think this is an issue with the site being set to NOT being responsive. Need to do a little more testing to be sure.
