### ISSUE TITLE
External link in articles won't take a query parameter that's a question mark

### ISSUE THREAD

**Issue by johnquest** [CuBoulder/express_mono#496]
some_url/register/?id=klsjdkjfkjksjdf
Gets truncated to some_url/register

**Comment by johnquest** [comment]
This fixes urls with a query but now breaks urls without a query. Redirect isn't set for urls without a query.

**Comment by AlanBCole** [comment]
@kevincrafts @jwfuller Is this still an issue. I can not reproduce it locally. I have created two links within an article:
1. https://loremipsum.io/generator/?n=5&t=s
2. https://www.fillmurray.com/640/360

Both seem to link correctly.
