### ISSUE TITLE
Remove option for having a site be non-responsive

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express_mono#517]
We still have a few sites out there that have chosen to have their site not be responsive, which causes issues on mobile devices, can cause issues on small desktop devices, and can impact the SEO of sites.

We should remove this option to be sure that all sites are set to display properly when viewed on a mobile device.

**Comment by AlanBCole** [comment]
How do our users normally go about toggling site responsiveness?

**Comment by AlanBCole** [comment]
Never mind. I believe I found it!

**Comment by cathysnider** [comment]
@kevincrafts @AlanBCole In addition to removing the choice, the code should also force the site to be responsive. Or should that be another ticket?
