### ISSUE TITLE
Filter publications by emails of person nodes on sites, filter by person type

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express_mono#523]

**Comment by AlanBCole** [comment]
@jwfuller @kevincrafts I am not sure what 'person type' this issue is referring to, or if the 'person nodes' and 'person type' are different. Are they both drupal/Express entities?

**Comment by jwfuller** [comment]
@AlanBCole There is a content type called `Person`; that content type has a field for specifying a `Type` of person which allows sites to group faculty vs administrators for example.
