### ISSUE TITLE
Cache results from experts.colorado.edu

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express_mono#531]

**Comment by AlanBCole** [comment]
@kevincrafts @jwfuller Is any kind of special caching necessary? Is Using Varnish what you had in mind? I have been making requests against the databases used in this epic and performance seems pretty good, so I am not sure caching is necessary. What do either of you think?

**Comment by jwfuller** [comment]
@AlanBCole I think the intention is to create a cache table in the DB/memcache. We want this to be able to minimize requests to the Experts DB (one person vs 1000 sites is a very different load) and to give us some additional resilience in case Experts goes down (ie, during normal operation don't clear the cache until a new value can be obtained)

**Comment by AlanBCole** [comment]
@jwfuller Oh, yes, that makes sense! Thanks.
