### ISSUE TITLE
Identify path patterns that include p1 values in express 

### ISSUE THREAD

**Issue by jeor0980** [CuBoulder/express_mono#543]
Causing issues during migration

**Comment by cathysnider** [comment]
Discovery: Google doc https://docs.google.com/document/d/1G9GUUZkQpmVl4a28T27sesyhe-XRrfGG4j3lyD9Zf9g/edit

**Comment by cathysnider** [comment]
CK Editor grabs base path settings here; uses it to build links: https://github.com/CuBoulder/express_mono/blob/dev/modules/contrib/ckeditor_link/plugins/link/plugin.js#L59

**Comment by jwfuller** [comment]
@jwfuller Will out what the `p1` variable is in `settings.php` file and grep the code base for references.

**Comment by jwfuller** [comment]
We use `base_url` which is a safe variable and `cu_path` which is not safe.

**Comment by jwfuller** [comment]
Instances of `cu_path`

https://github.com/CuBoulder/express_mono/blob/dev/modules/features/cu_search/cu_search.install#L19-L27
https://github.com/CuBoulder/express_mono/blob/dev/modules/features/cu_wysiwyg/cu_wysiwyg.module#L18-L44 (also uses `cu_sid`)
https://github.com/CuBoulder/express_mono/blob/dev/tests/behat/features/bootstrap/FeatureContext.php#L156-L180 (also uses `cu_sid`)

Instances of `cu_sid` which may also not be safe

https://github.com/CuBoulder/express_mono/blob/dev/modules/custom/cu_core/cu_core.install#L82-L91
https://github.com/CuBoulder/express_mono/blob/dev/modules/custom/cu_core/cu_core.module#L43-L54
https://github.com/CuBoulder/express_mono/blob/dev/modules/features/cu_wysiwyg/cu_wysiwyg.module#L18-L44 (also uses `cu_path`)
https://github.com/CuBoulder/express_mono/blob/dev/tests/behat/features/bootstrap/FeatureContext.php#L156-L180 (also uses `cu_path`)

Places that use `www.colorado.edu`

https://github.com/CuBoulder/express_mono/blob/dev/modules/custom/express_settings/express_settings.module#L301-L314
https://github.com/CuBoulder/express_mono/blob/dev/modules/features/cu_wysiwyg/cu_wysiwyg.module#L18-L44
https://github.com/CuBoulder/express_mono/blob/dev/tests/behat/features/bootstrap/FeatureContext.php#L156-L180
