### ISSUE TITLE
Article slider block displays wrong link color

### ISSUE THREAD

**Issue by ekellagher** [CuBoulder/express_mono#548]
The article slider block displays the wrong link color.
Here is a site with this issue
https://www.colorado.edu/mcnair/ 

![Screen Shot 2020-05-18 at 4 24 24 PM](https://user-images.githubusercontent.com/638275/82265442-3842dd80-9924-11ea-8712-9859dca02580.png)

**Comment by cathysnider** [comment]
Analysis: An Article Slider, with background set to one of the lighter colors in Block Designer (white, light gray, tan, light blue, medium blue, light green) and placed on a dark region such as Slider region, has visually hard-to-read link color.
