### ISSUE TITLE
warning: count(): Parameter must be an array or an object that implements       [warning] Countable Table.php:789

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express_mono#566]
James thinks this is coming from xmlsitemap

**Comment by jwfuller** [comment]
`drush help` can also produce the warning

**Comment by AlanBCole** [comment]
@jwfuller @kevincrafts Any other advice for reproducing this? `drush help` doesn't do it for me.

**Comment by jwfuller** [comment]
@AlanBCole You may need to enable the SEO bundle to enable the xmlsitemap module

**Comment by cathysnider** [comment]
Not sure how to duplicate the warning. Enabled SEO bundle; rebuilt site map; went to Configuration >> Logging and errors and chose "errors and warnings". I'm getting these errors; but not the "warning:count()" error

<img width="1375" alt="Screen Shot 2020-08-07 at 1 13 33 PM" src="https://user-images.githubusercontent.com/638275/89680321-f89aea80-d8af-11ea-9064-e7c229efe590.png">

**Comment by jwfuller** [comment]
@cathysnider did you trying running `drush help`?

**Comment by cathysnider** [comment]
@jwfuller yes
