### ISSUE TITLE
Increase the number of results in CKEditor Link

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express_mono#571]
The CKEditor Link module makes it very easy for editors to create links in the WYSIWYG editor to other content on their site by allowing them to search by node title and then create a link to that content in the correct way - node/[NodeID].

However, we currently have this configured to only return 10 results.  In a site with a lot of content, the content you are wanting to link to may not show up in that 10 results.  For example, if I want to link to the Research page on the Homepage site, the Research page will never show up because there are many pages that have research in them, which may cause someone to end up linking to the full url instead.  The configuration options for this allow us to increase the returned nodes all the way to 100, though I think I would suggest 30 or 40 might be a good start.

**Comment by jwfuller** [comment]
@kevincrafts Is going to investigate how linking works when you use various types of path based links.

```
/about
/p1/about
www.colorado.edu/about
https://www.colorado.edu/about
```

**Comment by kevincrafts** [comment]
Interesting thing I had not thought about before, but if we use url patterns at all (like articles for instance), the internal url is a little different.  Consider these two urls:

1. https://www.colorado.edu/today/media
2. https://www.colorado.edu/today/2020/05/26/chancellor-cu-boulder-welcome-students-back-campus-covid-19-ready-fall-semester

The internal path for the first url is "media" so one might think it's just the rest of the url after the site url...

But the second url is "chancellor-cu-boulder-welcome-students-back-campus-covid-19-ready-fall-semester" - If you tried adding the date part you would get an error.

**Comment by jwfuller** [comment]
@kevincrafts Is going to look into improving the sort. Increasing the list to a large number only temporarily solves the problem and decreases the UX.

**Comment by kevincrafts** [comment]
Sorting seems to be created order. I made a number of nodes that had the same word in their titles and they were presented in the order they were created.

I'm not sure any type of sorting makes sense here.

**Comment by kevincrafts** [comment]
Team discussed options, decided there wasn't any change that we could make here that would make any impactful change.
