### ISSUE TITLE
Remove Content Editor role from role filter on /admin/people page

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express_mono#574]
Content Editor is still a choice in the Role filter. The role has been removed; it can be removed from the filter as well. 

/admin/people

![contentEditorRoleFilter](https://user-images.githubusercontent.com/638275/82935291-0d6f0f80-9f4a-11ea-82c8-b5846c770af5.jpg)

**Comment by kevincrafts** [comment]
Closing this issue as it is more of a symptom of #576
