### ISSUE TITLE
Update cu_core for legacy express url variables

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express_mono#580]
https://github.com/CuBoulder/express_mono/blob/dev/modules/custom/cu_core/cu_core.install#L82-L91

https://github.com/CuBoulder/express_mono/blob/dev/modules/custom/cu_core/cu_core.module#L43-L54

**Comment by AlanBCole** [comment]
This issue is not a high priority as it deals with logging issues only. It is still important of course. Moving it back to New Issues pipeline.

**Comment by jwfuller** [comment]
Closing until this is required to be fixed by a new hosting provider.
