### ISSUE TITLE
 Fix or Remove This link to get help

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express_mono#581]
https://github.com/CuBoulder/express_mono/blob/dev/modules/custom/express_settings/express_settings.module#L301-L314

**Comment by AlanBCole** [comment]
@kevincrafts @jwfuller Is the code linked to above used anywhere? Also the endpoint used in the form's action attribute has a 404 response. Is this part of the problem we need to fix for this issue?:
- https://github.com/CuBoulder/express_mono/blob/b7118b28c56af4fa18732ccf5c2d0442b7ec5ab5/modules/custom/express_settings/express_settings.module#L304

**Comment by AlanBCole** [comment]
This code is not being used as far as I can tell so I am removing it from the epic #543 and putting it back into the New Issues pipeline.
