### ISSUE TITLE
Fix the test for Pathologic in WYSIWYG

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express_mono#582]
https://github.com/CuBoulder/express_mono/blob/dev/tests/behat/features/bootstrap/FeatureContext.php#L156-L180

**Comment by AlanBCole** [comment]
@kevincrafts @jwfuller I the function `pathologic_save()` actually being used in a test? I have not found it being called anywhere or tied to a .feature. I am guessing that I have simply not found it.

**Comment by jwfuller** [comment]
It doesn't look like the test is called, this may be the area where it was intended `express/tests/behat/features/Express/cu_wysiwyg/cu_wysiwyg_pathologic.feature`

**Comment by AlanBCole** [comment]
The code linked to above seems not to be used anywhere. Also, the `express/tests/behat/features/Express/cu_wysiwyg/cu_wysiwyg_pathologic.feature` seems to fail as well. In general this test, both in FeatureContext and .feature file, probably needs to be rewritten or removed as it isn't doing much at the moment.
