### ISSUE TITLE
Overridden feature 'CU Linkchecker'

### ISSUE THREAD

**Issue by jwfuller** [CuBoulder/express_mono#602]
This is the most commonly overridden feature. Is is supposed to be overridden and should be added to the exclusion list? Or do we need to fix something?

**Comment by AlanBCole** [comment]
@jwfuller I have never seen this feature overridden locally? Is it enabled by default?

**Comment by jwfuller** [comment]
@AlanBCole It is part of the Search Engine Optimization bundle
