### ISSUE TITLE
Allow heading tags to be used with the expand shortcode

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express_mono#609]
Currently the expand shortcode only allows you to input plain text for the title, and then renders that text within a link.

However, as these are used on sites to create lists of frequently asked questions, the resulting code isn't very friendly for screen readers.  If we could add an argument to the shortcode of what heading to use, we could have better structured content that would be more accessible.

We can't just make these all headings, because we don't know the surrounding structure of the page, which is why we would need to give the option of what heading to use (h2-h6) and have it default to it's current output so we wouldn't cause any problems with existing pages.

**Comment by kevincrafts** [comment]
Many sites use the expand shortcode rather than the FAQ page or Expandable blocks because it allows more flexibility in content order.  For instance, it is much easier for site editors to create a page with many paragraphs with groups of expandable shortcodes in between them rather than creating multiple text blocks and expandable blocks.

In many cases, these expandable shortcodes are preceded by headings which making scanning the document with a screen reader a little more accessible.  However, adding additional headings to these shortcodes would improve the page structure for accessibility and SEO.  

In addition, sometimes the expandables do not have a preceding heading and the expandable title should serve as a heading.  Adding a preceding heading such as "Frequently Asked Questions" does not solve this problem.

Even if the site editor used the more complicated method of adding multiple text blocks and expandable blocks, the expandable block does not have an option for setting the titles to be headings.

The expandable elements at the bottom of [this page](https://www.colorado.edu/infrastructure-sustainability/infrastructure-mitigation-efforts) are a good example of why the links should be headings instead of plain links.  Do not dismiss this example because the expandable elements are at the bottom of the page.

The current format of the shortcode is as follows:

`[expand title="Water quality" style="regular"]While not related to COVID-19 transmission, one side effect of remote learning and work arrangements has been the potential for water quality impacts. All domestic water on campus is supplied by the City of Boulder drinking water plants and is continually monitored to ensure the water supply is clean and meets all regulatory requirements.  With buildings being vacant or only minimally occupied, stagnant or standing water in plumbing systems can degrade the water quality over time. To ensure that the water in the plumbing systems does not remain stagnant for long periods, FM and EH&S personnel are proactively flushing the campus water systems each week.  As building occupancy is increased, the concern for potential degradation of water quality will lessen as more water is used on a daily basis.[/expand]`

I am suggesting we can add a heading argument like:
`[expand title="Water quality" style="regular" heading="h3"]While not related to COVID-19 transmission, one side effect of remote learning and work arrangements has been the potential for water quality impacts. All domestic water on campus is supplied by the City of Boulder drinking water plants and is continually monitored to ensure the water supply is clean and meets all regulatory requirements.  With buildings being vacant or only minimally occupied, stagnant or standing water in plumbing systems can degrade the water quality over time. To ensure that the water in the plumbing systems does not remain stagnant for long periods, FM and EH&S personnel are proactively flushing the campus water systems each week.  As building occupancy is increased, the concern for potential degradation of water quality will lessen as more water is used on a daily basis.[/expand]`

which would wrap the title argument in the requested heading tag. By not providing a heading argument I think we should change the default argument to be 'strong'.

**Comment by jwfuller** [comment]
Going to implement `strong` tags to improve accessibility while balancing the risks of having lots of headers to define and update

**Comment by kevincrafts** [comment]
Closed because after looking at this more found that we added this functionality more than a year ago.
