### ISSUE TITLE
Embed JIRA Service Desk form

### ISSUE THREAD

**Issue by ekellagher** [CuBoulder/express_mono#610]
The Office of Data Analytics has requested to use embed code from JIRA: 

The system we have is Jira Cloud + Jira Service Desk. 
We will save ODA $10,000 annually if we can make this change with your help.
What we have: A jira service desk project with a “widget” that adds a Contact Us button when the javascript code below is added to a page.
Code snippet:
<script data-jsd-embedded data-key="a47c4e7f-5a0a-464c-b670-9fc296dd8e15" data-base-url="https://jsd-widget.atlassian.com" src="https://jsd-widget.atlassian.com/assets/embed.js"></script>
When Contact us is clicked the FCQ Help form displayed below appears. 
When the user clicks send, the form makes an api call to jira service desk and creates a request ticket. There is no need to code this, it’s out of the box with the widget we are using.
The FCQ Help header color can be configured to meet CU standards and we think the form will pass accessibility testing, but will want to confirm.
<img width="1312" alt="JIRA" src="https://user-images.githubusercontent.com/16137919/86295023-f22f9980-bbb2-11ea-82e5-8665f561eb15.png">

I can demo this on a call if that would be helpful. Feel free to reach out!

Renae Dahiya
Assistant Director of Development
Reporting & Analytics
University of Colorado Boulder
303-492-6104

Extra Resources to help with the evaluation of this request
Atlassian security: https://www.atlassian.com/trust/security
VPAT: https://www.atlassian.com/accessibility

**Comment by geoss** [comment]
Hi WebExpress,

We'd live to have this completed by August 15th.  It seems like a very minor request, from our perspective.  Would love to have an ETA as soon as possible as its in important business process improvement for us.  Thanks!  -Seth Spielman

**Comment by jwfuller** [comment]
Discussed in our project management meeting, will we deal with this as a one-off solution rather than a platform feature
