### ISSUE TITLE
Datepicker missing previous next buttons

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express_mono#615]
![image](https://user-images.githubusercontent.com/349713/86832293-37d9df80-c055-11ea-8941-6a2dc84854a1.png)

We've removed the JQuery UI styles a long time ago but apparently nobody ever noticed they were missing from the date picker.

**Comment by jwfuller** [comment]
Going with a very targeted CSS solution, we are not going to pull the whole jQuery stylesheet back in.
