### ISSUE TITLE
Import express_slate_bundle

### ISSUE THREAD

**Issue by jeor0980** [CuBoulder/express_mono#62]
https://github.com/CuBoulder/express_slate_bundle

**Comment by cathysnider** [comment]
Review:
Enabling the Slate Express Bundle works: 
 1. Link "Add Slate Form Bean Embed" (content/embeds/add/et_slate_form_bean) is added to Add Embed page (admin/content/embeds/add)
 1. The Slate Form Bean Embed can be placed with Layout
 1. The Slate Form Bean Embed can be placed with Context. 
 1. Site Owners can add a Slate Form Bean Embed

Result: This works.

**Comment by cathysnider** [comment]
Question: Enabling the SEB did not enable "Embed Templates - Slate Form Block" -- Is this module necessary? 
![Screen Shot 2019-10-08 at 12 30 00 PM](https://user-images.githubusercontent.com/638275/66424249-82490580-e9ca-11e9-91c3-7da264896fff.png)

**Comment by jwfuller** [comment]
That works as designed for the moment, @kevincrafts and I are talking about the best pattern for embeds like these.
