### ISSUE TITLE
Improve filter function to include a notation for nested terms

### ISSUE THREAD

**Issue by jwfuller** [CuBoulder/express_mono#625]
Client reported that you can arrange Department terms into parent/child relationships, and that there is a `- ` added on the edit view for people_list_page. They want that same kind of representation on the front end as well.

https://github.com/CuBoulder/express_mono/blob/27516aaf438ff622b0987b9134cd590221efd959/modules/features/people_content_type/people_content_type.module#L408

**Comment by kevincrafts** [comment]
While we can make an indication that the terms are nested, I think that then requires we need to rewrite the query functions to include child terms if a parent term is selected.  Much of this was added to articles a couple years back.

**Comment by AlanBCole** [comment]
@jwfuller @kevincrafts Is this what you are talking about (adding a '-' to a department term)?
<img width="433" alt="Screen Shot 2020-08-24 at 3 44 38 PM" src="https://user-images.githubusercontent.com/23508839/91099734-180c7400-e621-11ea-957b-69db6ae951b3.png">
