### ISSUE TITLE
Missing commits from Faculty Publication Bundle

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express_mono#631]
It seems that some commits that were merged to the feature/41 epic are no longer in the code:

Issue: https://github.com/CuBoulder/express_mono/issues/584

Commit: https://github.com/CuBoulder/express_mono/commit/8a4fd198ac400e3a10741df111fa1ed221cc4f12

Pull request: https://github.com/CuBoulder/express_mono/pull/587

Current code in feature/41 branch: https://github.com/CuBoulder/express_mono/blob/feature/41/modules/custom/cu_faculty_publications_bundle/cu_faculty_publications_bundle.info

**Comment by AlanBCole** [comment]
@kevincrafts @jwfuller This is odd. I can see that PR #587 was merged, by me. It seems simple enough just to merge branch feature/41-584 into feature/41 as a fix.

**Comment by AlanBCole** [comment]
@jwfuller @kevincrafts PR #586 is also missing from feature/41

**Comment by jwfuller** [comment]
Found the missing commits. Issue occurred when a branch was force pushed, force push has been disabled for all branches
