### ISSUE TITLE
RSS Feed not validating because of timeout

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express_mono#632]
We received a support ticket regarding the following url:

https://boulder.joinhandshake.com/external_feeds/6168/public.rss?token=nZPyI4SwMYK3hh4patnZjtK33H-3ThQ_TO9nbETWg3r3RxUhqQnK-Q

The user reported that the form won't submit because it says the rss feed is not valid.  After some local testing, the feed is failing validation because of a timeout issue:

![image](https://user-images.githubusercontent.com/349713/88200128-f6bffe80-cc02-11ea-8d1e-e076b4b61901.png)

While the url does return valid xml quickly in the browser, it doesn't seem to do so when requested by drupal_http_request.

**Comment by jwfuller** [comment]
Check user agents, compare CLI tools to Drupal methods, check for domain specific issues.

**Comment by AlanBCole** [comment]
I have tried other rss feeds without problem. I am investigating what the issue may be with this particular rss feed url.

**Comment by AlanBCole** [comment]
The url given above doesn't pass the link widget/field's validation. The cu_rss_block.module code doesn't even called.

**Comment by AlanBCole** [comment]
@jwfuller @kevincrafts I am getting the following response with the url above using `drupal_http_request()`:
- HTTP/1.1 426 Upgrade Required
date: Tue, 11 Aug 2020 23:01:31 GMT
server: envoy
content-length: 0

**Comment by jwfuller** [comment]
@AlanBCole Is there any more to the response? Often it will say what you need to upgrade to

**Comment by AlanBCole** [comment]
@jwfuller No. Nothing more to the response that I have found.

**Comment by AlanBCole** [comment]
I see that the `drupal_http_request()` uses the protocol `tcp_socket/ssl`. Could this be part of the problem? I see that other tools (like node.js etc) use `tls`. I am always unclear about their differences.

**Comment by AlanBCole** [comment]
I should have asked this earlier, but, are we absolutely sure that the url included in this issue's description is correct?

**Comment by AlanBCole** [comment]
For now, taking myself off of this issue. I have not found any more information about it. I will take it up again in the future when I able to do so.

**Comment by AlanBCole** [comment]
This is what request looks like (when using drupal_http_request at least):
- `GET /external_feeds/6168/public.rss?token=nZPyI4SwMYK3hh4patnZjtK33H-3ThQ_TO9nbETWg3r3RxUhqQnK-Q HTTP/1.0
User-Agent: Drupal (+http://drupal.org/)
Host: boulder.joinhandshake.com`

You can see there that the outgoing request uses HTTP/1.0. Above you can see, in a previous comment, that headers passed along in the server's response states `HTTP/1.1 426 Upgrade Required`, telling us that we must upgrade to HTTP/1.1 for this request to work.

**Comment by AlanBCole** [comment]
The request line referred to just above is built in https://github.com/CuBoulder/d7core/blob/main/includes/common.inc#L967 of D7 core's common.inc (the drupall_http_request function).

**Comment by AlanBCole** [comment]
Maybe we need to use/create a different http client for similar requests as this? Or adapt `drupal_http_request()`?

**Comment by jwfuller** [comment]
1.0 is hard coded into [Drupal core](https://git.drupalcode.org/project/drupal/-/blob/7.x/includes/common.inc#L967). I also found two [core](https://www.drupal.org/project/drupal/issues/2242123) [issues](https://www.drupal.org/project/drupal/issues/106506)

The best solution may be to look at something like https://www.drupal.org/project/httprl, which I think we have considered before.

**Comment by jcsparks** [comment]
Incompatibility with D7 and the specified feed.  Will eventually be resolved with D9.
