### ISSUE TITLE
Update the Localist Block for Past Events

### ISSUE THREAD

**Issue by ekellagher** [CuBoulder/express_mono#640]
Localist now has a[ new past events events feature ](https://support.localist.com/7-new-features-you-wont-want-to-miss/)but we need to update our widget URL. I tested out the days parameter on our current block and received an error that I could only use numbers in the field

Here is the info from localist: You can now have a rolling past events Widget — i.e. “the last 30 days”. For example, once you’ve generated your Widget URL you can replace the days parameter with &days=-30 to indicate that the Widget should pull events from the previous 30 days. 

We have a couple request for a past events feature so I feel this would be useful to our web express / localist users.
Help Scout #4056, #3759

**Comment by kevincrafts** [comment]
This is a duplicate of #514
