### ISSUE TITLE
Allow Faculty Publications block to inherit information on a person node

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express_mono#643]
For larger departments, this could be an easy way to add this content if you could add a single block via context vs adding individual blocks.

**Comment by kevincrafts** [comment]
If there are no results for the experts database, this block should return no content, which results in the block being empty, and not being included in the page.

The purpose of this block would be able to place a single block on many pages at once, and a block with "There are no results for this user" would probably lead to requests for that message to be removed.

**Comment by AlanBCole** [comment]
I have been working on this with the following assumptions (please correct if I am mistaken):
1. A user will create a new context (at /admin/structure/context/add)
2. This user will select 'Node type'->'Person' is selected from the Conditions drop-down/select-list
3. This user selects 'Blocks'->'Faculty Publicaltions' and adds it to a page region from the Reactions drop-down/select-list
4. The selected block will now show up on all Person pages with a Person's publications listed in zero configuration required from user/site-editor
