### ISSUE TITLE
Error Message after switching out of masquerade mode

### ISSUE THREAD

**Issue by ekellagher** [CuBoulder/express_mono#644]
I used masquerade mode to trouble shoot a user issue on https://www.colorado.edu/lab/damrauergroup/
I tried to edit a page on the site as the user - confirmed the user error of not being able to save content. then tried to switch back to my account.

When I clicked switch back I got this error
![Switch back](https://user-images.githubusercontent.com/16137919/90263725-4b732580-de0d-11ea-9f9d-db2d220a22e2.JPG)
When I refreshed the page I got this access denied screen
![unswitch](https://user-images.githubusercontent.com/16137919/90263779-5c239b80-de0d-11ea-9645-1bae75e3c624.JPG)

**Comment by cathysnider** [comment]
I'm unable to duplicate. Steps: I signed in to several sites, including but not limited to Damrauer Group, using my secondary identiKey with administrator role, same role as Emily has. I masqueraded as a user with the Site Editor role. I was able to navigate as that user, and I was able to switch back to myself with no problem.

**Comment by jwfuller** [comment]
We think this is specific to the node, there are more than 1000 inputs, which overflows the apache limit we have configured.

**Comment by kevincrafts** [comment]
This is the same page that we were having other issues on because of the amount of images that are on the page.  When this form is submitted we run into a too many variables error. When trying to switch back and forth between users on this form, we run into the same error.
