### ISSUE TITLE
Enforce title field length on article node type

### ISSUE THREAD

**Issue by jeor0980** [CuBoulder/express_mono#679]
```
Uncaught exception 'PDOException' with message 'SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'title' at row 1' in /data/atlas/code/cores/drupal/drupal-7.72/includes/database/database.inc:2227
```

Bug can be reproduced by maxing out title field (255 characters)

Questions:
- At what point does this break SQL?
- Where is this limit defined?
- Is 255 chars enough?

**Comment by jeor0980** [comment]
Exception source: 

 `/cumuseum/node/add/article`

**Comment by cathysnider** [comment]
For references, here's a sentence with 255 characters (including spaces): 

Even though the CU Museum of Natural History is closed, you can still see one of its most popular exhibits: a 60 million-year-old triceratops skull that has long been the centerpiece of the museum's Paleontology Hall; 3D Triceratops scan featured on 9News

**Comment by kevincrafts** [comment]
This is the default node title field, so it's not defined in our code necessarily.

**Comment by cathysnider** [comment]
Plain Old Drupal will cut off any excess after the 255 character limit and allow you to go forward. Web Express will throw error "The website encountered an unexpected error. Please try again later."
