### ISSUE TITLE
Permission to forms

### ISSUE THREAD

**Issue by ekellagher** [CuBoulder/express_mono#682]
The Administrator permission level is not able to access form content using the edit link or results link on the webform admin page. They are able to get around this by clicking on the form title and then clicking the edit link or results link in the editing toolbar.

It would be more efficient if a site Administrator could access editing a form and form results on the forms admin page

**Comment by cathysnider** [comment]
Emily Kellegher reports that the problem was solved with a secure permissions rebuild.
