### ISSUE TITLE
Add COVID-Dashboard Web Component JS

### ISSUE THREAD

**Issue by brookestevens** [CuBoulder/express_mono#687]
Create a module for adding  a web component for the COVID-19 Stats.

**Comment by AlanBCole** [comment]
@brookestevens Do you mind if I assign this issue to only you? Since you already have a start on the vue component. I could grab another issue listed in the epic #691.

**Comment by brookestevens** [comment]
@AlanBCole Yeah, that's fine with me

**Comment by brookestevens** [comment]
Use this for the resource ID 1IF1JT4wzb38827Mklm0E2PEBnYekwN9l-Il0mChScsg

**Comment by jwfuller** [comment]
We are not going to chase the dashboard design
