### ISSUE TITLE
As a SO/ SE I would like to add a zoom meeting link to the People List Page table view contact info column

### ISSUE THREAD

**Issue by ekellagher** [CuBoulder/express_mono#690]
With the increase in online learning we need to add a field for an online meeting link. It would be nice to have it work with select various virtual tools such as Zoom, Teams, Google Hangouts. They would need a field for the URL and one for the link text.

The people list page has a table view that it would be be great to add this link the contact column but it might also be good to include it in the list view display too

If you try to put the information in any of the other fields it does not retain its HTML link because it is pulled into the people list page as summary content that is not formatted.

**Comment by kevincrafts** [comment]
Is the link field on the person content type not appropriate for this?

**Comment by jwfuller** [comment]
The link field can cover some of this need. We are also concerned about creating Zoom spam.
