### ISSUE TITLE
As a user I need to add components to a page on my Web Express site

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express_mono#691]
Editors need the ability to add components to pages on their site in regions they specify.

Examples of components:
1. A Slate or Salesforce form
2. A widget from an approved vendor service
3. A custom data visualization

We can accomplish this by creating a component bean type that will allow a site editor to place the component wherever they want with the Web Express layout tools. When creating a component:
1. the user will choose which type of component they want (from a list we define)
2. a form will be loaded containing the appropriate fields for the component type
3. the values should be stored in a custom table

When rendering the component, we can provide a template for each component type that will insert the saved values.

**Comment by kevincrafts** [comment]
After confirming a recent request for a new chat widget and talking it over with James, I'm going to start this over with this model:

1. An embed entity which can load a form based on defined (by us) types of embeds.
2. A bean type that can pick from the saved entities for the "I need to place and render this javascript in this theme region" requirement.
3. A context reaction that can be used for the "I need to place this javascript code on this path(s)" requirement.

**Comment by jwfuller** [comment]
Closed for https://github.com/CuBoulder/express_mono/milestone/2

**Comment by jwfuller** [comment]
Closed for https://github.com/CuBoulder/express_mono/milestone/3

**Comment by jwfuller** [comment]
Reopening for review
