### ISSUE TITLE
Analytics IDs not correct.

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express_mono#704]
Through some digging James and I found multiple issues with Google Analytics IDs and the Web Express Service.

1. We have an ID (UA-25752450-1) that is [set in the settings.php file](https://github.com/CuBoulder/atlas/issues/654) that is then duplicated via Google Tag Manager.
2. We have an ID (UA-105731679-1) that is for sites on the Web Express service, but is [only added to a site if another Google Analytics ID is added](https://github.com/CuBoulder/express_mono/blob/dev/modules/custom/express_settings/express_settings.module#L453)

**The problems with this are:** 

1. We have an ID that is used for campaign tracking that doesn't work correctly because it is added twice.
2. The service-wide ID is not actually service-wide, and is only tracking sites where a custom ID has been added.  If that account is being used to look at analytics of the service, it's not correct.
3. We need to add the service-wide ID to all sites on the service, without duplicating that ID on sites that may have added a custom ID.  If we add the service-wide ID to the settings.php file, we need an update hook to remove it from the sites database.

**Additional questions:**

1. Do we want the service-wide analytics ID output on the dev and test environments?
2. Do we want the service-wide analytics ID output on sites that are not launched?

**Comment by jwfuller** [comment]
https://github.com/CuBoulder/atlas/issues/654

**Comment by jwfuller** [comment]
We deciced to remove the ID in code and use it in place of the one currently used in Atlas
