### ISSUE TITLE
Import cu_google_cse_admin_bundle

### ISSUE THREAD

**Issue by jeor0980** [CuBoulder/express_mono#71]
https://github.com/CuBoulder/cu_google_cse_admin_bundle

**Comment by jwfuller** [comment]
Steps to use CSE:

1. Log into https://cse.google.com/cse/ as websupport@colorado.edu
1. Create New search engine for that site
  1. Sites to search: www.colorado.edu/[PATH]
1. Fill in Search engine name with same pat
1. Click CREATE (the Title will be populated as Colorado.edu/PATH)
1. Copy the number that follows cx= (but before the : or %3A characters in Google Chrome) in the cse.google.com URL. You will also need the string after the : or %3A as that is the ID field
    ```
    https://cse.google.com/cse/create/getcode?cx=016234341123453004813%3Aq_syefrjxlq```
1. Go to https://www.colorado.edu/webcentral/admin/content/google-cse
1. Click Add Google CSE and fill our the form with the following fields:
    ```
    Path: [PATH]
    Id: [Code after :] (numbers in purple from step 5)
    Creator: [CX] (numbers in red from step 5) (this number is automatically filled in)```
1. Save the Node
1. Export the XML file by clicking the Google CSE XML tab
1. In the Google CSE site, click the Edit search engine below the New search engine button, select Colorado.edu/[PATH] from the list .  
1. Click the Advanced tab and expand CSE context
1. Click the Upload XML file button
1. Upload the Colorado.edu-[PATH].xml file

**Comment by jwfuller** [comment]
@cathysnider Is going try this using here demo site

**Comment by jwfuller** [comment]
Goal is to have this be something that is easily configurable for any instance.

**Comment by cathysnider** [comment]
Step 7 cannot be complied with; there is no https://www.colorado.edu/webcentral/admin/content/google-cse page to go to.

**Comment by jeor0980** [comment]
The cu_google_cse_admin_bundle served two purposes:

1) The module lived in old webcentral, as a way to keep track of all the CSE’s we had in place,
2) You could use the module to export xml with our “customized”  template. The customization was mostly for the look and feel, but it did include the nonprofit = true setting. I used the same template and this no longer works. https://github.com/CuBoulder/cu_google_cse_admin_bundle/blob/master/templates/google-cse-xml.tpl.php

The reason the module was created was to eventually be able to add promotions to a cse and export them using the module itself, there’s no magic we add to make cse’s ad-free.
Google used to pick up automatically if was being used for non-profit, if the sites being searched were in the .edu domain, I alsotested that and that is also no longer the case.

We will have to jump through the hoops and set up a verified admin, or find out if someone else has already done so.

**Comment by jeor0980** [comment]
The process for creating ad-free Google CSE has changed a little bit.
1. Use the websupport@colorado.edu account when creating a new CSE
2. In the setup panel go to the ‘Admin’ tab and click the “Add” button to add msappaccess@colorado.edu as a user
3.  Open a ticket with oit requesting that someone with access to that account (Messaging and Collaboration) accepts the invitation as a user
4. Wait about 24 hours for the CSE to switch over to ad-free

**Comment by cathysnider** [comment]
Log into cse.google.com/cse as websupport@colorado.edu - (it has IdentiKey)
Create New search engine for that site
Fill out fields:
- Sites to search: www.colorado.edu/[PATH]
- Name of the search engine: www.colorado.edu/[PATH]
Click "Create"
Message: "Congratulations! You've successfully created your Custom search engine"
Click button "Control Panel"
- Note down Search Engine ID: 016005321760733004813:iilirnsx71y
- Note down Public URL: https://cse.google.com/cse?cx=016005321760733004813:iilirnsx71y
Click Admin tab
Add a user to your custom search engine: msappaccess@colorado.edu
... to be continued

**Comment by cathysnider** [comment]
## Template for ServiceNow Ticket:

This ticket is for the Messaging and Collaboration team:

The WebExpress Team is updating the Google CSE for the sites that we maintain. Your account, mcappaccess@colorado.edu, should have received an email invitation, informing you that websupport@colorado.edu has invited you to contribute to their custom search engine “www.colorado.edu/[PATH]” Please login to the mcappaccess email account and accept the invitation. To accept the invitation, click the site link in the invitation, and choose ‘Include me as an Administrator’ in the subsequent dialogue box.  Thank you. Let us know if you have any questions.

Name
Web Express
Strategic Relations and Communications (edi
