### ISSUE TITLE
Warning from cu_core.install

### ISSUE THREAD

**Issue by jwfuller** [CuBoulder/express_mono#714]
Noticed during 7.73 core update, may be occurring during cron

```
Use of undefined constant authenticationMode - assumed                 [warning]
'authenticationMode' (this will throw an Error in a future version of
PHP) cu_core.install:379
```

**Comment by cathysnider** [comment]
I almost always change the authenticationMode variable when testing locally; I saw this error locally but thought it was caused by my local actions. I will look into this further.

**Comment by jwfuller** [comment]
I think adding single quotes to the array key will fix it https://github.com/CuBoulder/express_mono/issues/714
