### ISSUE TITLE
Improve local coding standards tools

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express_mono#716]
For D7. By adding Coder module.

**Comment by jwfuller** [comment]
Goes in admin debug bundle

**Comment by AlanBCole** [comment]
I am not sure how the Coder would be best used... Are we looking for IDE integrations/linters for Drupal standards? Or something to be included in our express_mono repo's composer.json file that we can run locally via the command line (after running `composer install`)? 

I can see the first option (IDE linter) being easy assuming that there is a good linter plugin already etc. I am not sure we want to add even more to the mono repo. I suppose, in the future, with recent versions of Drupal a composer approach could work quite well, but maybe not for our D7 codebase.

**Comment by AlanBCole** [comment]
I will investigate more options for improving local coding standards.

**Comment by AlanBCole** [comment]
Some 'official' Drupal setup advice or Visual Studio Code (which at least a few of us use): https://www.drupal.org/docs/develop/development-tools/configuring-visual-studio-code

**Comment by AlanBCole** [comment]
I am planning on adding work for this issue to the cu_debug_admin_bundle repository. Please look there for the pr to be created soon!

**Comment by AlanBCole** [comment]
I have moved the solution to this issue to our cu_debug_admin_bundle repository and created 2 issues there related to getting the Drupal coder module set up:
1. Visual Studio Code: https://github.com/CuBoulder/cu_debug_admin_bundle/issues/3
2. PHPStorm setup: https://github.com/CuBoulder/cu_debug_admin_bundle/issues/4

Our team uses both of those editors so it seemed good to create an issue for both.
