### ISSUE TITLE
Academics Affairs has blank core role radio button on people invite page

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express_mono#718]
https://www.colorado.edu/academicaffairs/admin/people/invite

Randomly searching through other sites hasn't turned up anyone else with this problem.

![blankCoreRole](https://user-images.githubusercontent.com/638275/94075096-c427b300-fdb7-11ea-8281-b53710c29282.jpg)

**Comment by ekellagher** [comment]
Another site with similar issue: https://www.colorado.edu/odece/admin/people/invite

**Comment by jwfuller** [comment]
In the past this comes from role deletion. May be related to https://github.com/CuBoulder/express_mono/issues/112

**Comment by kevincrafts** [comment]
Can I get a db from this @jwfuller ?
