### ISSUE TITLE
View form submissions text change

### ISSUE THREAD

**Issue by ekellagher** [CuBoulder/express_mono#726]
Some Web Express users are confused about the View Submissions Permission. In most permission use cases the word "view" means the user can see content but not edit or interact with it.

In our case a user with View Submissions Permission, can also delete submissions, download etc

I would like suggest the following text change for clarity

ALLOW THE FOLLOWING USER(S) TO VIEW FORM SUBMISSIONS.
to
ALLOW THE FOLLOWING USER(S) TO MANAGE FORM SUBMISSIONS.

**Comment by jwfuller** [comment]
@ekellagher What URL does this text appear on?

**Comment by cathysnider** [comment]
@jwfuller It appears on node/#/edit for webforms.
