### ISSUE TITLE
Article Slider links are broken

### ISSUE THREAD

**Issue by jwfuller** [CuBoulder/express_mono#729]
https://github.com/CuBoulder/express_mono/blob/73444a78e6609a0ce4855d537540b271a29bce2e/modules/features/cu_article/modules/cu_article_slider/templates/article-slider-node.tpl.php#L3

The node and ID are no longer passed through `l()`, the link function so the resulting URL is relative to the page rather than the instance. Bug was introduced in https://github.com/CuBoulder/express_mono/pull/626

**Comment by kevincrafts** [comment]
Also noticed there is a css error with the gradient so I'm going to fix that as well.
