### ISSUE TITLE
Remove interface for adding new LiveChat widgets

### ISSUE THREAD

**Issue by jwfuller** [CuBoulder/express_mono#744]
Now that JS Includes are merged, we can start closing down LiveChat

**Comment by AlanBCole** [comment]
## Questions:
- Is simply deleting the cu_livechat_bundle not satisfactory?:
- Are there steps that have been decided on already?
- Is there a need to notify users who may be using livechat previously to the cu_js_include module?

**Comment by jwfuller** [comment]
- Is simply deleting the cu_livechat_bundle not satisfactory?
    - No, people are using the bundle and deleting it would break their sites
- Are there steps that have been decided on already?
    - Generally, we deprecate a feature, migrate people to the new alternative, disable the code, delete the code. 
- Is there a need to notify users who may be using livechat previously to the cu_js_include module?
  - Yes, we need to do this as part of this. Atlas Statistics or it's successor can help us with this
