### ISSUE TITLE
Responsive Table shortcodes don't seem to be working

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express_mono#774]
https://www.colorado.edu/demos/cathys-sandbox/webexp-design/table-styles

Responsive Table:

The extra long table is enclosed in a [ responsive-table ] shortcode and should be showing a horizontal scrollbar at the bottom. Instead, it is being cut off in the middle of a column. 

<img width="977" alt="Screen Shot 2020-12-07 at 3 43 57 PM" src="https://user-images.githubusercontent.com/638275/101414308-18184300-38a3-11eb-82cc-cee1531fd882.png">

**Comment by jwfuller** [comment]
@kevincrafts to confirm bug

**Comment by kevincrafts** [comment]
Two problems here:
1. The shortcode requires a "breakpoint" value to know when the table should start scrolling.
2. This site isn't responsive, and we removed the setting to make it responsive, so somehow it's still in fixed mode.

**Comment by cathysnider** [comment]
I'll pass that info on to Emily so she can update the documentation on how the shortcode works.

**Comment by jwfuller** [comment]
@cathysnider will close once this is communicated.

**Comment by cathysnider** [comment]
Communicated
