### ISSUE TITLE
Replace TravisCI

### ISSUE THREAD

**Issue by jwfuller** [CuBoulder/express_mono#777]
TravisCI is changing the way that they support [open source](https://blog.travis-ci.com/oss-announcement). We are anticipating that we will not be able to continue to use this service.

Some options

- GitHub Actions
- CircleCI
- On-premises Jenkins

**Comment by AlanBCole** [comment]
in the .travis.yml file there is a variable used that I do not see a definition for ($TRAVIS_BUILD_DIR). Where is this coming from? On our Travis repo?

**Comment by cathysnider** [comment]
@AlanBCole I believe it is an environmental variable set by Travis CI. https://docs.travis-ci.com/user/environment-variables/

"TRAVIS_BUILD_DIR: The absolute path to the directory where the repository being built has been copied on the worker."

**Comment by AlanBCole** [comment]
@cathysnider Thanks! That is kind of what I figured.

**Comment by AlanBCole** [comment]
### Needs for CI replacement solution
For the purpose of being sure that our chosen option can provide what we need, I thought it would be good to provide a summary of what our requirements are. Please add or correct these lists as needed.

#### Requirements
- Set up an environment suitable for Drupal 7 with tests (linux, php 7.2.x, mysql, composer)
- CI process to be run on each PR/merge to dev branch in the express_mono repository
- Integrate with SauceLabs?
- Send notifications of build status

#### Outline of Build Process
1. Install Drush
    - https://github.com/CuBoulder/express_mono/blob/dev/tests/travis-ci/install.sh#L4
2. Install behat
    - https://github.com/CuBoulder/express_mono/blob/dev/tests/travis-ci/install.sh#L9
3. Clone our d7core repository
    - https://github.com/CuBoulder/express_mono/blob/dev/tests/travis-ci/install.sh#L14
4. Move and rename express_mono (the action takes place in this repository so no need to clone it) to d7core/profiles/express
    - https://github.com/CuBoulder/express_mono/blob/dev/tests/travis-ci/install.sh#L15
5. Give file permissions etc
    - https://github.com/CuBoulder/express_mono/blob/dev/tests/travis-ci/install.sh#L25-L26
6. Create mysql database "drupal"
    - https://github.com/CuBoulder/express_mono/blob/dev/tests/travis-ci/setup.sh#L7
7. Install express Drupal installation profile
    - https://github.com/CuBoulder/express_mono/blob/dev/tests/travis-ci/setup.sh#L34
    - Also make a copy of initial database -> https://github.com/CuBoulder/express_mono/blob/dev/tests/travis-ci/setup.sh#L40
8. Run tests:
    - https://github.com/CuBoulder/express_mono/blob/dev/tests/travis-ci/behat-tests.sh

**Comment by AlanBCole** [comment]
I am thinking that Github actions would be our best bet as a replacement. Other opinions welcome, though. My thinking below:
1. There are options to meet all of our requirements as listed above
2. We are already using github so having it handle pull request actions etc seems like the least complicated option
3. Since the express_mono repo is a public repository running gihub actions is free!
4. We already are using some actions/workflows in express_mono so why not add another?

**Comment by AlanBCole** [comment]
### Other questions:
1. Can we use MariaDB?
2. If so what version expect?
3.

**Comment by AlanBCole** [comment]
Actions that we can use in build steps:
- https://github.com/saucelabs/sauce-connect-action
- https://github.com/marketplace/actions/composer-php-actions
- https://github.com/actions/checkout

**Comment by jwfuller** [comment]
> ### Other questions:
> 
>     1. Can we use MariaDB?
> 
>     2. If so what version expect?

We use `5.5.5-10.1.29-MariaDB` in prod. You can use it for testing, but it is not a requirement

**Comment by AlanBCole** [comment]
It turns out that both php and composer are installed on an action's container. Maybe this is due to the fact that express_mono contains a large amount of php code? Cool though!

**Comment by AlanBCole** [comment]
Reading up on Behat mink extension. It looks like it is being removed in the future. https://github.com/Behat/Behat/issues/1296. There is no date given. In any case the repository has not seen any new work for a few years. So for future use of behat testing we should start thinking of a replacement for this extension, either one of those mentioned in the issue or by adding a context of our own that defines the steps we use -> "* I am on ...", "* I press ...", etc.

It does seem like mink itself is being maintained. At least it has been worked on in the last year .

**Comment by jwfuller** [comment]
@AlanBCole I wouldn't worry about replacing that currently, we can deal with that later
