### ISSUE TITLE
Images displaying at incorrect sizes

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express_mono#782]
A [recent change](https://github.com/CuBoulder/express_mono/commit/be2aebba54e7e9e6df306309c7ffab0802edae78#diff-ab151a7d6f10bde0a9a3b9b188f87cc973936b24888ca8c37c007ad85c9721c3R25) to the people css has caused small and medium images to not display at their proper sizes.  This change is forcing these image styles to display at 100%, even though the image size may be much smaller, resulting in very pixelated images.  Example: https://www.colorado.edu/cwa/2020/12/07/dont-label-me-cwa-book-study-virtual-event

**Comment by kevincrafts** [comment]
What is looks like now vs what it should look like...
![Screen Shot 2020-12-14 at 9 47 54 AM](https://user-images.githubusercontent.com/349713/102109657-886a1b80-3df1-11eb-8412-fbf5991acd71.png)

![Screen Shot 2020-12-14 at 9 48 01 AM](https://user-images.githubusercontent.com/349713/102109683-8e5ffc80-3df1-11eb-9b5e-4c80e1fc6fe6.png)

**Comment by AlanBCole** [comment]
@kevincrafts Do you know how this image was added to the page? Shortcode? Also when I go to the page you have linked to in the description I see the page "what it should look like..." page. Were changes made to that page in particular so that the book cover shows up correctly?

**Comment by AlanBCole** [comment]
#### Using the following steps (sorry if they are way off...) I have not been able to reproduce this:
1. Upload a picture by going to `/node/add/file`
    - This adds a node with some urls for different image sizes.
    - Copy the url for the small image
2. Create a new article:
    - click the image tab/short code and paste in the image url
    - select "right" option in Alignment dropdown
    - save the image
3. Add some text with the styles set to "lead"
4. Add a bunch of other text with no styles option selected (just regular text)
5. Click save and look at the page.
6. See that the image is floated to the right as expected

**Comment by AlanBCole** [comment]
Also, I am not sure how the recent changes you linked to apply as the css classes `image-small` or `image-medium` are not found in the page linked or the one produced by following the steps I outlined above.

**Comment by cathysnider** [comment]
@AlanBCole Here's now to add an image to a page:
Add or Edit a Basic Page
Below the body field, there is button to upload an image. 
Upload an image, then place cursor in body field where you'd like image to appear. 
Select Image Size from Style drop-down, then click 'Insert'
<img width="492" alt="Screen Shot 2021-01-07 at 1 16 51 PM" src="https://user-images.githubusercontent.com/638275/103941324-eab1f580-50eb-11eb-8ed5-76539c7f257f.png">

**Comment by AlanBCole** [comment]
The reason I could not reproduce the bug is because I recently spun up a new Lando environment and did not enable the cu_people_bundle or people_content_type modules. I have reproduced the bug.
