### ISSUE TITLE
Integration with Jobs

### ISSUE THREAD

**Issue by ekellagher** [CuBoulder/express_mono#784]
Client has requested integration with Jobs site, they would like to embed the application forms on their site.
https://secure.helpscout.net/conversation/1370819266/5308?folderId=1414566

"I'm wondering if there is a way to take jobs we post here: https://www.colorado.edu/jobs/
And make them auto fill onto our website? Like the campus events, newsletter archive or news archive.

**Comment by jwfuller** [comment]
Duplicate of https://github.com/CuBoulder/express_mono/issues/65
