### ISSUE TITLE
JS Includes missing permission

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express_mono#787]
The js includes module is missing the permission for anonymous and authenticated users to view js includes.

I needed to manually change this permission on the homepage, financial aid, bursar, and registrar websites on 12/22.

**Comment by cathysnider** [comment]
The permissions are already included in the module. See cu_js_includes.permissions.inc.
A site has to be loading permissions from code, though. Ensure that Secure Permissions has not been disabled.

**Comment by jwfuller** [comment]
@cathysnider I am guessing that this doesn't work on sites that are updated to the new code, I suspect that we need a secure permission rebuild update hook

**Comment by jwfuller** [comment]
This is still an issue
