### ISSUE TITLE
JS includes shows on Profile Module Manager report

### ISSUE THREAD

**Issue by jwfuller** [CuBoulder/express_mono#788]
```
Profile Module Manager | Some required modules either not enabled or extra modules are enabled. Check cu_js_includes
```
This bundle should not appear on this report, it is allowed to be enabled.

**Comment by cathysnider** [comment]
Question: Won't this problem fix itself once JS Includes is added to one of the current bundles?

**Comment by jwfuller** [comment]
@cathysnider I don't think so, but am not sure

**Comment by cathysnider** [comment]
@jwfuller The answer is yes, once cu_js_includes is added as a dependency to a bundle, as requested https://github.com/CuBoulder/express_mono/issues/791, it will no longer be flagged in the Profile Module Manager report. When that issue is resolved, this one will be as well.
