### ISSUE TITLE
Postwide Region in Minimal Theme forces images to be left justified

### ISSUE THREAD

**Issue by ekellagher** [CuBoulder/express_mono#789]
When a site is using the Minimal theme, you are not able to place a text block with a centered image in the post wide region.
We had a support ticket #5363 (site: https://www.colorado.edu/research/ai-institute/) with this issue and I am able to replicate it on a test site
On the AI Institute site - I hacked a temporary solution
To test this though, I created a block "NSF logo text block" with a centered image. If you place it in the post wide region it will display left aligned.

My test site is https://www-test.colorado.edu/p1363adeea72/
All you need to do is change the theme to say Spirit and the image will shift to the center as it is designed to be. We tell clients that their content will not change when they change themes but this is not the case in this situation.

**Comment by kevincrafts** [comment]
I did some testing with this on a local site on the release/4.4.2 branch and did not have an issue with this. I when trying previous branches I ran into the issue cause by #782.
