### ISSUE TITLE
Filter Tips page is viewable by anonymous users

### ISSUE THREAD

**Issue by ekellagher** [CuBoulder/express_mono#790]
A compose tips page is public when you are logged out of a site
just type /filter/tips at the end of a URL such as https://www.colorado.edu/webcentral/filter/tips

I discovered this when working with a client on their site map
![filter tip](https://user-images.githubusercontent.com/16137919/103566864-fdc08d80-4e7f-11eb-99b8-a2de0f9159d6.JPG)

**Comment by AlanBCole** [comment]
I do not believe that this is in our codebase. Is this something that we should fix?

**Comment by jwfuller** [comment]
The page comes from a contrib module, we want to suppress it via our codebase
