### ISSUE TITLE
Add js_includes as a dependency for one of the bundles so users can enable it.

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express_mono#791]
We should attach this to an existing bundle so it's easy to enable and add an update hook for that bundle so it will be enabled for sites that already have that bundle enabled.

Kevin will look through the bundles to see which one it should be part of.  Since this module uses context, it should probably be part of a module that also enables the context UI.

**Comment by kevincrafts** [comment]
I think cu_advanced_layout_bundle might be the leading candidate so far.

**Comment by cathysnider** [comment]
Questions brought up by Emily:
Are they moving the digital campaign embeds to work with includes or will those still be separate? Slate forms is part of includes but it also has it's own bundle so will they remove that slate bundle? What is the process to enable the LiveChat feature should I create a new form for people to fill out?

**Comment by kevincrafts** [comment]
1. Some parts of the digital campaign bundle should be removed at some point. This includes the Slate bundle but all of those will need to be migrated.  The embeds/tracking pixels are handled by GoogleTagManager so I think the only thing left might be the funnel pages, which could also be moved into another bundle. 

2. The Livechat, and any other functionality that is part of the js includes module will be automatically enabled for any site that  enables its parent bundle.  There will be no need for a request form.
