### ISSUE TITLE
Create endpoint for site metrics

### ISSUE THREAD

**Issue by jwfuller** [CuBoulder/express_mono#793]
Prometheus uses a scrape model rather than a push model for gathering metrics. We need each site to have an endpoint for scraping these metrics. We should secure this information transfer because it will  contain user lists. This will replace `atlas_statistics`

**Comment by AlanBCole** [comment]
### Some more background for this issue: 

- Prometheus is the tool we use to gather performance data from our websites/services.
- The 'scrape' or 'pull' model for gathering data means that Prometheus initiates http requests to services, assets, websites etc to gather desired data in contrast to services themselves initiating communication and sending data to Prometheus. This is why we need an endpoint for Prometheus to receive Prometheus' requests
- How does atlas_statistics work presently?
### Questions
- What exactly does 'secure' mean here?
    - simply sending all data over https?
    - removing sensitive details before sending http response? If so, what is too sensitive to include in this response?
- What are the data we wish to gather for useful metrics? (Look into atlas_statistics)
- What are the shortcomings of atlas_statistics that we need to remedy with a new endpoint?

#### List of objectives/goals for this issue:
-

**Comment by jwfuller** [comment]
> What exactly does 'secure' mean here?

Anonymous users should not be able to access the data, I would look at token based authentication as a start

> What are the shortcomings of atlas_statistics that we need to remedy with a new endpoint?

I don't think the Web Express side has any clear failures, Atlas is not the best place to store this data and that is the main thing we are fixing

> Will the Atlas API still need to be involved?

Not with metrics

**Comment by AlanBCole** [comment]
@jwfuller Thanks. One more question regarding the Atlas API. It looks like it is used [here](https://github.com/CuBoulder/express_mono/blob/dev/modules/custom/atlas/atlas_statistics/atlas_statistics.module#L89-L92) to get some site details. Is there another way to get these? Or are they needed?
