### ISSUE TITLE
Feedback Form has little scroll bar on right side

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express_mono#796]
possibly caused by css #cu-feedback {overflow-y: scroll;}

https://www.colorado.edu/cmci/contact-us

<img width="301" alt="Screen Shot 2021-01-08 at 2 05 18 PM" src="https://user-images.githubusercontent.com/638275/104064125-96297b80-51ba-11eb-88df-888d6986eae9.png">

<img width="241" alt="Screen Shot 2021-01-08 at 2 04 22 PM" src="https://user-images.githubusercontent.com/638275/104064055-742ff900-51ba-11eb-9da1-fd6a1b7641f2.png">

**Comment by kevincrafts** [comment]
What browser was this on? I haven't been able to get that to show up on my test site. Also not sure if it's something with that particular form.

**Comment by kevincrafts** [comment]
I checked https://www-test.colorado.edu/cmci/ in Safari, Chrome, and Firefox and did not see this issue.

**Comment by jwfuller** [comment]
Not significant, won't fix
