### ISSUE TITLE
Overridden feature 'CU People'

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express_mono#804]
Many sites are reporting the error that CU People feature has been overridden.

some examples:
https://www.colorado.edu/admin/reports/status
https://www.colorado.edu/business/admin/reports/status
https://www.colorado.edu/asmagazine/admin/reports/status

**Comment by jwfuller** [comment]
@cathysnider What part of the feature is overridden?

**Comment by cathysnider** [comment]
Strongarm has been overridden

**Comment by jwfuller** [comment]
@cathysnider Which variable in strongarm?

**Comment by cathysnider** [comment]
xmlsitemap

**Comment by jwfuller** [comment]
Re-export the feature and make sure that testing passes, particularly in regards to sitemap

**Comment by kevincrafts** [comment]
We need to be sure of the status of the xml sitemap module during a site install.  If this module is only enabled with the seo bundle, the seo bundle should be enabled before the people feature gets exported again.
