### ISSUE TITLE
Add Translate to Web Express

### ISSUE THREAD

**Issue by ekellagher** [CuBoulder/express_mono#824]
I noticed that https://www.cu.edu/ now has a translate option run by Google Translate and wanted to know if we could add this feature to Web Express. We have a lot of sites that have content in Spanish but are unable to change the page language to reflect this and it causes accessibility issues. Having a translate option would help our clients to not have to create duplicate content as well.
Examples
https://www.colorado.edu/cumuseum/museum-home
https://www.colorado.edu/cumuseum/exhibits
https://www.colorado.edu/admissions/international/spanish
https://www.colorado.edu/cuengage/en-espanol
https://www.colorado.edu/smokefree/humo-politica-de-libre
https://www.colorado.edu/even/en-espanol
https://www.colorado.edu/lasc/2011/09/18/rmclas-2012-annual-conference-cfp
https://www.colorado.edu/rioverdearchaeology/
https://www.colorado.edu/studentaffairs/la-vision-de-la-vice-canciller
https://www.colorado.edu/fiske/showtimes/apollo-11-50th-anniversary/nuestra-luna-especial
https://www.colorado.edu/center/cuchange/encuesta-de-la-salud-en-espanol

**Comment by jcsparks** [comment]
Translations are difficult at scale.  A bad translation can be worse than just allowing the browser to do a machine-language translation.  We can revisit this in the future but doing this at our scale will be very expensive.
