### ISSUE TITLE
Upgrade to PHP 7.4

### ISSUE THREAD

**Issue by jcsparks** [CuBoulder/express_mono#825]
PHP 7.2 is end of life as of November 2020.  We should see if there's any reason that we can't upgrade to 7.4 at this point.  

Should be compatible with D7 according to : https://www.drupal.org/docs/7/system-requirements/php-requirements

**Comment by jcsparks** [comment]
Need to have dashboards in Grafana working to evaluate before we update.  Should also check to see if PHP8 is compatible when we're ready to update.

**Comment by johnquest** [comment]
Updating PHP from remi repo 7.2.34-3 (release 3) to 7.2.34-4 causes content grids to become un-editable. Error is "Theme Hook not found" in CU callout bundle. Release 4 from remi is a backported patch from PHP 7.3.28.

**Comment by jcsparks** [comment]
Upgrade completed, some minor compatibility warnings that will be taken care of via tickets for those specific issues.
