### ISSUE TITLE
Block Designer Theme creation bug

### ISSUE THREAD

**Issue by ekellagher** [CuBoulder/express_mono#833]
If a site does not have any Block Designer Themes, A Site Editor may click on the block designer tab and click the "Create a Block Designer Theme" link and create a new theme. 

<img width="403" alt="SE add theme" src="https://user-images.githubusercontent.com/16137919/119405795-126eb800-bc9f-11eb-8b74-b0714f824be3.png">

Once a Theme has been created though they are unable to edit the theme or go to the Design Admin page.

<img width="316" alt="SE create new theme" src="https://user-images.githubusercontent.com/16137919/119405727-f703ad00-bc9e-11eb-99d7-a0f79452d9f9.png">

**Comment by cathysnider** [comment]
Two options:

**1. Remove ability to add Block Designer themes:**
 According to the User Roles master plan, Site Editors do not make decisions on the design of the site. That ability belongs to the Site Owners.  See User Roles 3.0 https://docs.google.com/spreadsheets/d/1fJk-k9BUySz3a7tMpMvEKKRfcToGeER1MBLajKxFi6s/edit#gid=0 

Therefore, the ability to access the Block Designer Theme page should be removed from the Site Editor role. 

Edit: To complete this, remove permission 'administer block designer themes' from site_editor array. https://github.com/CuBoulder/express_mono/blob/dev/modules/custom/express_block_designer/express_block_designer.module#L190

**2. Add ability to access all themes:**
The other option is to add the permission 'administer express theme picker' to the Site Editor role. This would expand the abilities currently assigned to the Site Editor role, allowing them to administer WebExp Themes.

**Comment by cathysnider** [comment]
I checked with Emily about the level of access for Site Editors. She confirmed:
"Site Editors should not be able to create block designer themes, they can design blocks individually but not create universal site block themes."
