### ISSUE TITLE
Update features contrib module to fix PHP deprecation warnings

### ISSUE THREAD

**Issue by jeor0980** [CuBoulder/express_mono#841]
I'm seeing a lot of these warnings on our logs after updating to PHP 7.4 

```
PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated in /data/atlas/code/profiles/express/express-4.4.7/modules/contrib/features/includes/features.context.inc on line 17
```
Updating the features module should fix this problem, this issue has been resolved in drupal.org https://www.drupal.org/project/features/issues/3086633

Features Module: https://www.drupal.org/project/features

**Comment by jcsparks** [comment]
This should be fixed when the latest updates are pushed out.  There's an updated version of the ldap contrib module that fixes this.

**Comment by jcsparks** [comment]
Updates have been pushed out but because of Log4j, we don't have any visibility into the issue currently.  Evaluate again in the new year once all of the logging systems have been patched and we have visibility into the systems again.

**Comment by jcsparks** [comment]
Think this is fixed.... reopen if we're still having the issue.
