### ISSUE TITLE
Google Analytics 4

### ISSUE THREAD

**Issue by jcsparks** [CuBoulder/express_mono#846]
GA4 is out now and apparently tracks different information from UA.  The on-campus GA experts are suggesting that we add both into Express for tracking currently.  There is some concern that UA may be deprecated and removed by Google in the future.  Additionally we're missing out on the additional information tracked by GA4 by not adding that in now.  

The counter argument is that it's another tracker and we're giving even more information about our users to Google if we add it.  

Need to evaluate and make a choice.

**Comment by jcsparks** [comment]
Maybe look at https://matomo.org/ as an alternative to GA

**Comment by AlanBCole** [comment]
### after a brief (incomplete) look

It seems like GA4 is a complete rewrite of Google's analytics service. It does not seem that more data is gathered but it does change how data is collected. A big change is that cookies will no longer be used to track a user's browsing to and away from a given web page but rather a user's journey will be tracked somehow with AI (likely to avoid GDPR). Another change is the event model, and event driven nature, that triggers GA4 'hits' and how GA4 determines the opening and closing of a 'session'. 

I would say that OIT's concern that UA will be deprecated seems well founded as GA4 is the default analytics tool used for new accounts. However, I have I did not find an end of life announced for UA and many sites I found talked about using it along with GA4 (There is a way for a GA4 tag to be included -> https://support.google.com/analytics/answer/10447272?hl=en&ref_topic=9303319#zippy=%2Cdrupal). I would say that it might be best for us to wait until there is an update to the googleanalytics module to support the new GA4 service. Or it might be a perfect time to re-evaluate our analytics tool altogether and perhaps choose another one (for example matomo). In either case I think this will require a little more looking into before making a change.

Good documents:
- https://support.google.com/analytics/answer/9964640?hl=en#zippy=%2Cin-this-article

#### Possible Related Questions:
- How do we presently use Google Analytics?
    - What data is tracked?
    - How is it reported?
    - Who looks at the reports and what do they expect to see?

### Matomo
An open source alternative that I have not looked into yet.

**Comment by jcsparks** [comment]
Need to evaluate how we're implementing GA in the Express currently.  Determine how difficult it will be to add in GA4 with the current solution.

**Comment by jcsparks** [comment]
Not going to update to GA4 until Kevin Crafts is happy that it isn't breaking other things with tracking.   Will use GTM to add it in when the time comes.
