### ISSUE TITLE
Replace fonts.com fonts with an open source alternative

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express_mono#857]
Looks like we won't be renewing our contract with fonts.com next year, so we need to replace our font references with an open source alternative.

The CU System Brand Board will meet to decide which alternative will be used, but regardless, this needs to be completed and deployed before January when the license expires.

**Comment by kevincrafts** [comment]
Hero Unit block headings should be condensed.

**Comment by jcsparks** [comment]
Merged in chang with 4.4.7
