### ISSUE TITLE
Check to prohibit deleting the homepage fails if homepage is not set to node/NODEID

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express_mono#86]
Notice: Undefined offset: 1 in cu_home_page_form_alter() (line 18 of /user/express_local/data/code/profiles/express/express-3.1.0/modules/features/cu_home_page/cu_home_page.module).

**Comment by jwfuller** [comment]
Enable Advanced content bundle
Set homepage to `admin`
Visit a node edit form and see error
